2단계 - 조회 성능 개선하기
next-step/infra-subway-performance pull request #120
Opened 2021-12-25 11:24 UTC by haedoang

리뷰어님 안녕하세요! 2단계 PR 요청 드립니다 ! 😃 

질문사항이 있는데요! 

1) 쿼리 작성 문제에서 OR 조건이 있는 경우 UNION 이 성능이 더 좋다라고 하여 작성해본 결과 
성능이 오히려 더 떨어졌습니다. (쿼리를 첨부하여 문의드리려 했지만  삭제를 해버렸군요 😢 ) 리뷰어님은 어떻게 생각하시는지 궁금합니다

2) replication으로 master 서버의 부하를 줄이는 학습을 하였는데요 트랜잭션 단위로 master와 slave를 설정하였습니다
그러면 캐시가 적용될 경우에는 캐시가 더 먼저 작동을 할 것 같습니다
캐시  사용과 리플리케이션 사용. 어떤 방향이 더 좋은 방향일까요 ?  궁금합니다  🙏 

 그럼 이번에도 잘 부탁드립니다

2021-12-26 11:12 UTC, minsungryu requested changes
해동님 안녕하세요, 개인사정으로 리뷰가 늦어진 점 양해부탁드립니다.
몇 가지 코멘트를 남겼는데요, 확인해주시고 다시 리뷰 요청 부탁드릴게요~!
질문주신 부분은 별도로 코멘트를 남기도록 하겠습니다.

2021-12-26 11:12 UTC, minsungryu commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        return count;
count 변수를 사용하는 곳이 없다면 반환할 필요가 없지 않을까요?

2021-12-26 11:12 UTC, minsungryu commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        PageRequest pageRequest = PageRequest.of(5, 8); // 41~ 48
주석 대신 단언문을 통해 검증하는 것은 어떨까요?

2021-12-26 11:12 UTC, minsungryu commented on src/test/java/nextstep/subway/line/domain/LineRepositoryTest.java
> +    @DisplayName("page를 pk를 받아서 성능을 개선한다.")
성능을 개선하는 테스트라고 하지만 실제 테스트 코드는 성능에 대한 부분은 없어보입니다.
성능 테스트는 별도로 진행하고 검증하고 `@DataJpaTest`에서는 JPA 관련된 검증만 하는 것이 좋지 않을까요?

2021-12-26 11:12 UTC, minsungryu commented on src/test/java/nextstep/subway/line/domain/LineRepositoryTest.java
> +        );
lineResponse를 별도로 선언해주신 이유가 있을까요?
이 부분이 필요하다면 when절이 아닌 given절에 포함시키는 것이 의미에 맞지 않을까요?

2021-12-26 11:12 UTC, minsungryu commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        PageRequest pageRequest = PageRequest.of(0, 10); //5 ~ 14 기준이 pk
테스트를 이해하는데 혼동을 줄 수 있는 주석은 제거해주시는 것이 어떨까요?
필요하다면 설명을 추가하고 검증부에서 단언문을 통해 표현해볼 수도 있을 것 같습니다.

2021-12-26 11:12 UTC, minsungryu commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    @DisplayName("지하철 노선의 PK 기준으로 페이징 목록을 조회한다.")
인수 테스트에서 페이징 기능이 어떻게 구현되었는지 세부 내용은 노출하지 않아도 되지 않을까요?

2021-12-26 11:12 UTC, minsungryu commented on src/test/java/nextstep/subway/station/domain/StationRepositoryTest.java
> +        PageImpl<Station> stationPageImpl = new PageImpl<>(stations.getContent(), stations.getPageable(), stations.getTotalElements());
이 변수를 선언해주신 이유가 있을까요?

2021-12-26 11:12 UTC, minsungryu commented on README.md
> +    2) mysql `explain` 과 workbench 에서 제공하는 `explain ui` 기능으로 쿼리 성능 및 cost를 검증한다.
이미지를 첨부해주시는 것보다 개선 전후의 explain 결과를 제공해주시는게 확인하기 더 좋을 것 같습니다 :)

2021-12-26 11:19 UTC, minsungryu commented
> 1. 쿼리 작성 문제에서 OR 조건이 있는 경우 UNION 이 성능이 더 좋다라고 하여 작성해본 결과
성능이 오히려 더 떨어졌습니다. (쿼리를 첨부하여 문의드리려 했지만 삭제를 해버렸군요 😢 ) 리뷰어님은 어떻게 생각하시는지 궁금합니다

두 쿼리의 실행계획은 확인해보시고 어떤 이유로 성능이 떨어진건지 확인해보신걸까요?
OR 조건을 IN절로 대채해보면 어떨지, 인덱스를 적절히 추가하셨는지도 궁금합니다.

일반적으로 JPA, querydsl 이 UNION문을 지원하지 않기 때문에 특별한 경우가 아니면 개인적으로는 사용을 권장하고싶진 않습니다.


> 2. replication으로 master 서버의 부하를 줄이는 학습을 하였는데요 트랜잭션 단위로 master와 slave를 설정하였습니다
그러면 캐시가 적용될 경우에는 캐시가 더 먼저 작동을 할 것 같습니다
캐시 사용과 리플리케이션 사용. 어떤 방향이 더 좋은 방향일까요 ? 궁금합니다 🙏

캐시와 다중화는 전혀 다른 문제입니다.
다만 운영 환경에서 다중화는 필수이며 캐시는 필요에 따라 붙일 수도 안붙일 수도 있습니다.

2021-12-26 16:15 UTC, haedoang commented on README.md
> + - 웹 애플리케이션에서는 테이블의 내용을 1~20건 단위로 나눠서 보여주는 것이 일반적입니다. 테이블의 레코드를 일정 단위로 잘라서 조회하는 것을 페이징 쿼리라고 합니다.
네 감사합니다!

2021-12-26 16:17 UTC, haedoang commented on images/b/query.sql
> +
hospital 테이블이 programmer 테이블보다 row수가 적어서 드라이빙테이블로 선택헀습니다 
다시확인해보겠습니다!

2021-12-26 16:21 UTC, haedoang commented on images/a/query.sql
> +SELECT 현재활동인부서의_관리자_연봉_top5.사원번호, 사원.이름, 현재활동인부서의_관리자_연봉_top5.연봉, 현재직급.직급명, 사원퇴실기록.지역, 사원퇴실기록.입출입구분, 사원퇴실기록.입출입시간
조인쿼리로작성한줄알았는데 서브쿼리인가보군요! 
다시확인해보겠습니다

2021-12-26 16:21 UTC, haedoang commented on images/b/query.sql
> +         INNER JOIN hospital C ON B.hospital_id = C.id
확인해보겠습니다

2021-12-26 16:21 UTC, haedoang commented on images/b/query.sql
> +-- 1. Coding as a Hobby 와 같은 결과를 반환하세요. execution: 71 ms
재요청 시 반영하도록 하겠습니다

2021-12-26 16:22 UTC, haedoang commented on images/b/query.sql
> +  AND covid.programmer_id = programmer.id
네 알겠습니다

2021-12-26 16:23 UTC, haedoang commented on images/b/query.sql
> +WHERE A.id = D.hospital_id
네 알겠습니다

2021-12-26 16:23 UTC, haedoang commented on src/main/java/nextstep/subway/configuration/DatabaseConfig.java
> +//@EnableJpaRepositories(basePackages = {"nextstep.subway"})
죄송합니다

2021-12-26 16:24 UTC, haedoang commented on src/test/java/nextstep/subway/AcceptanceTest.java
> +@ActiveProfiles("dev")
네 반영하도록하겠습니다

2021-12-26 16:24 UTC, haedoang commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
죄송합니다 체크못했네요 반영하도록하겠습니다

2021-12-26 16:26 UTC, haedoang commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        노선_페이지_응답됨(pageRequest, response);
참고하겠습니다 감사합니다!

2021-12-26 16:26 UTC, haedoang commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        return count;
반영하도록하겠습니다

2021-12-26 16:27 UTC, haedoang commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        PageRequest pageRequest = PageRequest.of(5, 8); // 41~ 48
감사합니다 학습해보겠습니다

2021-12-26 16:28 UTC, haedoang commented on src/test/java/nextstep/subway/line/domain/LineRepositoryTest.java
> +    @DisplayName("page를 pk를 받아서 성능을 개선한다.")
감사합니다 혼동되는 표현을 사용했네요  반영하겠습니다

2021-12-26 16:31 UTC, haedoang commented on src/test/java/nextstep/subway/line/domain/LineRepositoryTest.java
> +        );
수정하도록하겠습니다

2021-12-26 16:31 UTC, haedoang commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        PageRequest pageRequest = PageRequest.of(0, 10); //5 ~ 14 기준이 pk
단언문에 대해학습해보겠습니다 감사합니다

2021-12-26 16:33 UTC, haedoang commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    @DisplayName("지하철 노선의 PK 기준으로 페이징 목록을 조회한다.")
네알겠습니다

2021-12-26 16:34 UTC, haedoang commented on src/test/java/nextstep/subway/station/domain/StationRepositoryTest.java
> +        PageImpl<Station> stationPageImpl = new PageImpl<>(stations.getContent(), stations.getPageable(), stations.getTotalElements());
프레젠테이션단에서 사용할 객체에 대한 테스트를 잘못사용한 것 같습니다 수정하도록하겠습니다.

2021-12-26 16:34 UTC, haedoang commented on README.md
> +    2) mysql `explain` 과 workbench 에서 제공하는 `explain ui` 기능으로 쿼리 성능 및 cost를 검증한다.
재요청시 변경하여 요청드리겠습니다 감사합니다.

2021-12-27 07:12 UTC, minsungryu commented on src/main/java/nextstep/subway/configuration/DatabaseConfig.java
> +//@EnableJpaRepositories(basePackages = {"nextstep.subway"})
어이쿠 죄송까지야 ㅠ.ㅠ
제 피드백은 개인적인 의견일 뿐입니다.
가벼운 마음으로 받아주시고 해동님 의견도 적극적으로 말씀해주세요 🙂

2021-12-29 15:55 UTC, haedoang commented on src/main/java/nextstep/subway/configuration/DatabaseConfig.java
> +//@EnableJpaRepositories(basePackages = {"nextstep.subway"})
아닙니다 ㅜㅜ 
피드백확인하면서 코드를 돌려보니 환경설정 제대로 하지 않아서 테스트도 깨지고 버그도 있어서  죄송스러울 따름입니다 🙇
피드백 반영하여 다시 요청드리겠습니다 감사합니다 🙏

2021-12-30 06:43 UTC, minsungryu approved these changes
해동님, 미션 완료하느라 고생 많으셨습니다!
몇 가지 코멘트를 추가로 남겨드렸는데요, 관련해서 고민해보시면 도움이 되지 않을까 싶습니다 🙂
새해 복 많이 받으세요!

2021-12-30 06:43 UTC, minsungryu commented on build.gradle
> +dependencies {q:q
앗 이거 지워주셔야 빌드가 돌아갈 것 같아요!

2021-12-30 06:43 UTC, minsungryu commented on queries/b/query5.md
> +FROM (SELECT id FROM member WHERE age >= 30 AND age < 40) AS a
서브쿼리는 지양해주시면 좋지 않을까요?

2021-12-30 06:43 UTC, minsungryu commented on src/main/java/nextstep/subway/configuration/CacheConfig.java
> +@Profile(value = {"local", "prod"})
다른 프로필을 위한 설정이 안보이는데 지정하지 않아도 괜찮은거 아닐까요?

2021-12-30 06:43 UTC, minsungryu commented on src/main/java/nextstep/subway/station/dto/StationResponse.java
> +    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
serdes 부분이 상당수 중복될 걸로 보이는데요
특별한 경우가 아니라면 공통 설정으로 해결이 가능하니 참고 부탁드려요 :)

2021-12-30 06:43 UTC, minsungryu commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        ExpectedPageResult expected = new ExpectedPageResult(5, 8, 100);
기댓값은 given절보다 하단의 then 위치에 넣어주시는게 가독성에 좋지 않을까요?

2021-12-30 06:43 UTC, minsungryu commented on src/test/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
기본 properties 파일에는 validate 또는 설정하지 않는 방법도 좋지 않을까요?
ddl-auto 설정은 위험하기 때문에 실제로 테스트에 사용할 프로필에만 설정해두는게 좋을 것 같은 생각이 듭니다.

2021-12-30 06:43 UTC, minsungryu commented on queries/b/query3.md
> +    ON programmer (hobby, student, years_coding);
복합 인덱스도 좋은데요 몇 가지 제약사항이 있어서 쿼리문을 신중하게 작성해야합니다.
해당 컬럼의 카디널리티가 높은지도 확인을 해보면 좋을 것 같습니다 :)

2021-12-30 06:43 UTC, merged

2021-12-30 06:44 UTC, haedoang commented on build.gradle
> +dependencies {q:q
ㅠㅠ아 죄송합니다!!

2021-12-30 06:46 UTC, haedoang commented on build.gradle
> +dependencies {q:q
PR 요청을 구분해서 올리려고 파일을 나눠서 commit을 하다가 그런것 같네요..
꼼꼼하게 봤어야 했는데 죄송해요!!

2021-12-30 06:56 UTC, haedoang commented on queries/b/query5.md
> +FROM (SELECT id FROM member WHERE age >= 30 AND age < 40) AS a
🙇  풀스캔을 해서 인덱싱을 사용하려고 서브쿼리로 구현하였던 것 같습니다! 
좀 더 고민해보도록 하겠습니다 감사합니다!!

2021-12-30 07:02 UTC, haedoang commented on src/main/java/nextstep/subway/configuration/CacheConfig.java
> +@Profile(value = {"local", "prod"})
감사합니다!

2021-12-30 07:03 UTC, haedoang commented on src/main/java/nextstep/subway/station/dto/StationResponse.java
> +    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
감사합니다!!

2021-12-30 07:06 UTC, haedoang commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        ExpectedPageResult expected = new ExpectedPageResult(5, 8, 100);
그렇군요! 
given 절에 테스트에 관련한 객체들을 정의하고 
then 절에 대해서는 테스팅모듈의 메서드만 사용하는것으로 생각했었는데요! 
말씀해주신 내용이 더 가독성에 좋은 것 같습니다 
감사합니다 앞으로 참고하도록하겠습니다!

2021-12-30 07:08 UTC, haedoang commented on src/test/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
내용 감사합니다! 앞으로 주의하도록하겠습니다

2021-12-30 07:10 UTC, haedoang commented on queries/b/query3.md
> +    ON programmer (hobby, student, years_coding);
인덱스 작성이 쉽지 않은 것 같습니다 😓 

피드백 주셔서 감사합니다

2021-12-30 07:32 UTC, haedoang commented on queries/b/query5.md
> +FROM (SELECT id FROM member WHERE age >= 30 AND age < 40) AS a
다시 검토해보니 조언 주신 내용이 더 나은 성능을 보여주는 것으로 확인하였습니다. 😅 
죄송합니다 😭 
```sql
SELECT covid.stay, count(*) as count
FROM member
         INNER JOIN programmer ON member.id = programmer.member_id
         INNER JOIN covid ON programmer.id = covid.programmer_id
         INNER JOIN hospital ON covid.hospital_id = hospital.id
WHERE programmer.country = 'India'
  AND member.age >= 20 AND member.age < 30
  AND hospital.name = '서울대병원'
GROUP BY covid.stay
ORDER BY NULL;
```

체크해주셔서 감사합니다 🙇 🙇