2단계 - 조회 성능 개선하기
next-step/infra-subway-performance pull request #127
Opened 2021-12-26 13:15 UTC by wangkdk

안녕하세요 리뷰어님!
2단계 조회 성능 개선하기  리뷰 요청드립니다.

데이터베이스에 대한 학습을 많이 해야겠다는 생각이 드는 미션 이였습니다.
쿼리 결과에 대해서는 이미지로 첨부하였습니다!

감사합니다!

2021-12-27 14:26 UTC, slamdunk7575 requested changes
안녕하세요~ 왕기님. 안정적인 서비스 만들기 잘 진행해주셨네요 👍
결과 이미지를 첨부 해주셔서 쉽게 확인할 수 있었습니다.
소소한 코멘트 남겨드렸는데 확인해보시면 좋을 것 같아요.
조금만 더 힘내주세요~!💪

2021-12-27 14:26 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +    public List<FavoriteResponse> findFavorites(LoginMember loginMember,
List를 반환하는 경우 Front 쪽에서는 `전체 페이지 사이즈 or 현재 페이지 정보`를 알 수 있을까요?
만약 위와 같은 부분이 고려되지 않았다면 `Page 인터페이스`와 구현체인 `PageImpl`에 대해 한번 살펴보시면 좋을 것 같아요.

2021-12-27 14:26 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +    @Transactional(readOnly = true)
쓰기 작업은 `Master`에서 하고 읽기 작업은 `Slave`로 하도록 잘해주셨네요 👍

2021-12-27 14:26 UTC, slamdunk7575 commented on README.md
> +ORDER BY p.id;
이부분은 인덱스 결과가 없는것 같아요 🥲 
`hobby, student, years_coding` 에 인덱스를 걸어보셨을까요?

인덱스 생성시 순서를 조절하면 성능을 개선해 볼 수 있는데요.
아래 내용도 참고해보시면 좋을것 같아요 :)

[[mysql] 인덱스 정리 및 팁](https://jojoldu.tistory.com/243)

2021-12-27 14:26 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/favorite/ui/FavoriteController.java
> +        Pageable pageable) {
아래처럼 설정해보면 좋을 것 같아요 :)

`@PageableDefault(size=5, sort = "id", direction = Sort.Direction.DESC) Pageable pageable`

2021-12-27 14:58 UTC, wangkdk commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +    public List<FavoriteResponse> findFavorites(LoginMember loginMember,
넵! Page 객체로 반환하도록 변경하겠습니다.

2021-12-27 15:00 UTC, wangkdk commented on README.md
> +ORDER BY p.id;
참고해서 반영해보겠습니다!

2021-12-28 12:35 UTC, wangkdk commented
안녕하세요 리뷰어님!
피드백 반영하여 다시 리뷰 요청드립니다.
인덱스의 경우 블로그를 참고하여 중복도가 낮은 순에서 높은 순으로 설정을 해보았고,
실행계획 으로 확인 결과 rows 수가 반으로 줄어든 것을 확인했습니다!  👍 

감사합니다!

2021-12-28 15:09 UTC, slamdunk7575 approved these changes
왕기님~ 피드백 반영해주신 부분 확인했습니다. 고생 많으셨어요 👍
남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다! 🎉

2021-12-28 15:09 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/favorite/ui/FavoriteController.java
> +        @PageableDefault(size = 5, sort = "id", direction = Sort.Direction.DESC) Pageable pageable) {
피드백 반영 잘해주셨네요 👍

2021-12-28 15:09 UTC, merged