2단계 - 조회 성능 개선하기
next-step/infra-subway-performance pull request #142
Opened 2021-12-28 14:49 UTC by lewisseo91

안녕하세요~! 
리뷰 해 주셔서 정말 감사합니다.

이번에 1단계 미션이 취소되면서 2단계 미션을 바로 PR 요청 보내게 되었습니다.
쿼리가 어려우면서 재밌다는 걸 깨닫게 되었습니다.
쿼리 보내는 것이 익숙치않아 여러 방면으로 찾아가면서 답을 찾아보았습니다.

잘 부탁 드립니다!

2021-12-29 15:53 UTC, na-mul requested changes
안녕하세요 동현님, 
쿼리 뿐만 아니라 어플리케이션 수정도 깊게 고민하여 진행하신 점 매우 인상적입니다.
한가지 코멘트만 추가적으로 개선이 있었으면 해요!
그리 어렵지는 않을 거에요. 한번만 더 확인해주셔서 다시 Request 부탁드립니다!
끝까지 화이팅입니다 🔥

2021-12-29 15:53 UTC, na-mul commented on src/main/java/nextstep/subway/station/ui/StationController.java
>      }
특히 응답도 Page객체로 잘 수정해주셨습니다.

2021-12-29 15:53 UTC, na-mul commented on src/main/java/nextstep/subway/station/domain/StationRepository.java
> +    @Query("SELECT s FROM Station  s WHERE id >= :offset")
커서 방식의 페이징을 잘 적용해주셨군요!! 성능 상 이점이 매우 크지요. 많이 칭찬드립니다.

2021-12-29 15:53 UTC, na-mul commented on README.md
> +  group by hobby DESC;
mysql 변수도 잘 활용해 주셨네요!! 👍

2021-12-29 15:53 UTC, na-mul commented on README.md
> +  hobby index로 지정 - full index scan으로 전환
- 전체적으로 이렇게 말로 써주신 것을 index 만드는 쿼리 등으로 작성해주실 수 있으실까요?

2021-12-29 15:54 UTC, na-mul commented
위 리뷰에서 마지막 코멘트만 개선해주시면 완벽할 것 같아요
 `hospital text -> varchar(255) 로 변경 후 index search 로 변경`와 같은 문구들 모두 쿼리로 변경 부탁드릴께요

2021-12-29 21:08 UTC, lewisseo91 commented
안녕하세요~ na-mul님
좋은 피드백 감사합니다!

제가 mysql workbench에서 더블 클릭으로 인덱스를 생성하고 하다보니
실제 쿼리가 어떻게 진행되는 지 잘 몰랐는데 
말씀해 주신 피드백보고 진행되는 action에 있는 쿼리에 주목할 수 있었습니다!

좋은 하루 되시길 바라요~!

2021-12-30 14:33 UTC, na-mul commented
실제 운영환경에서는 서버 작업을 할 때, ui로 작업을 허용하는 곳은 거의 없다고 보셔도 될 것 같아요. flyway 같은 툴을 사용할 때도 마찬가지구요! 결국 index 생성 등의 쿼리를 익혀두는 편이 매우 도움이 됩니다. 잘 진행해주셨습니다 👍

2021-12-30 14:36 UTC, na-mul approved these changes
안녕하세요, 동현님. 
index까지 잘 추가해주셨네요! 👏 approve하도록 할께요. 👍
짧은 미션이었지만, 역시 이 미션도 너무 중요한 미션이었네요.
앞으로 틈틈히 복기하시면서 더 능숙해지시길 응원드립니다!!
고생하셨습니다 🙇‍♂️

2021-12-30 14:36 UTC, merged

2021-12-30 14:54 UTC, lewisseo91 commented
좋은 조언 주셔서 정말 감사합니다.
쿼리가 생명이군요 
소중히 기억하겠습니다!! 좋은 팁 감사하고 올 한해 정말 수고 많으셨습니다.
조금만 더 화이팅입니다!!