2단계 - 조회 성능 개선하기
next-step/infra-subway-performance pull request #152
Opened 2021-12-30 10:18 UTC by minseokLim

1. 쿼리 최적화를 할 때, 툴은 Datagrip과 workbench를 같이 썼습니다. Datagrip이 익숙한데 visual explain 기능은 workbench에만 있는 것 같아서요. 
2. 쿼리는 Datagrip에서 스크린샷을 찍은 겁니다. 원래 텍스트로 README.md에 붙여넣으려다 너무 보기 힘들고 안 예쁜 것 같아서 이렇게 했는데, 생각해보니 리뷰어님이 리뷰하실 때 복/붙이 안되서 불편하실 수 있겠네요^^;; 쿼리 수행 시간 스크린샷은 workbench 입니다.

잘 부탁드립니다! 😄

2021-12-30 15:46 UTC, leeyohan93 requested changes
드디어 마지막 단계네요 👍
조금만 더 힘내주시기 바랍니다 🔥
몇가지 코멘트들을 남겨두었으니 확인 부탁드릴게요 :)

2021-12-30 15:46 UTC, leeyohan93 commented on src/main/java/nextstep/subway/station/application/StationService.java
> +    private Specification<Station> computeSpecification(final Pageable pageable) {
Specification을 사용해주셨는데, 개인적으로 Specification은 실무에서 사용하기에는 너무 복잡한 구조를 가지고 있어 사용을 지양해야 한다고 생각합니다 🤔  

Spring Data JPA 에서는 Pageable을 사용하는 것으로 페이징 요구사항을 잘 구현할 수 있는데 별도로 사용해주신 이유가 궁금합니다 😄

2021-12-30 15:46 UTC, leeyohan93 commented on src/main/java/nextstep/subway/station/ui/StationController.java
> +        @PageableDefault(size = 20, sort = "id", direction = Sort.Direction.ASC) Pageable pageable
하나의 페이지에 매우 큰 size가 설정되어 요청이 들어오면 어떻게 될까요 ? :)

이 부분을 방지해보면 좋을 것 같습니다 😄

2021-12-30 15:46 UTC, leeyohan93 commented on README.md
> +   * [X] **프로그래밍이 취미인 학생 혹은 주니어(0-2년)들이 다닌 병원 이름을 반환하고 user.id 기준으로 정렬하세요. (covid.id, hospital.name, user.Hobby, user.DevType, user.YearsCoding)**
`프로그래밍이 취미인 학생 혹은 주니어(0-2년)` 요구사항에 나온 조건은 `혹은` 이었는데요 !
where 절을 확인해주시면 좋을 것 같고 학생 여부에 대한이 dev_type 컬럼에 명시되어있을까요 ? 🤔 

조건을 수정해보면 인덱스를 설정해주셔야 될 수도 있겠네요 :)

2021-12-31 04:25 UTC, minseokLim commented on src/main/java/nextstep/subway/station/application/StationService.java
> +    private Specification<Station> computeSpecification(final Pageable pageable) {
저도 실무에서는 Querydsl을 사용합니다. Specification은 너무 복잡하죠😅  그럼에도 불구하고 Specification을 사용한 이유는, 이 요구사항 하나 때문에 Querydsl을 추가하는 건 너무 과도한 것 같다는 생각 때문이었습니다.

Pageable만으로 페이징을 구현하지 않고 이 부분을 추가한 이유는, 

```
select *
from station
order by id asc
limit 500, 100;   --> explain rows: 600

select *
from station
where id > 500
order by id asc
limit 0, 100; --> explain rows: 180
```

위의 쿼리보단 아래 쿼리와 같은 방식으로 하는 걸 추천한다고 강의 때 들어서입니다. 이렇게 하면 뒷 페이지로 갈 수록 성능이 떨어지는 걸 방지할 수 있다고 들었습니다. 실제로 explain 결과에서도 rows 수가 줄었고요.

근데 지금 좀 더 자세히 살펴보니 이상한 점이 많습니다; 

1. 페이지가 뒷쪽일 때만 성능상 이점이 있습니다. 앞쪽 페이지를 조회하는 아래와 같은 경우는 오히려 id 조건절을 추가하는 쪽의 explain 결과가 좋지 않게 나옵니다.
```
select *
from station
order by id asc
limit 100, 100; --> explain rows: 200

select *
from station
where id > 100
order by id asc
limit 0, 100; --> explain rows: 516
```
2. ID 값이 불연속적일 경우(중간 중간 삭제된 레코드가 있을 경우) 결과 값이 기댓값과 다르게 나올 수 있습니다.
3. Page 객체와의 통합이 어렵습니다. data-jpa에서는 page객체를 완성시키기 위해 쿼리의 where 조건절과 동일한 count 쿼리를 날려서 totalElements, totalPages 등을 계산하는데, 이 결과가 기댓값과 다르게 나오겠네요ㅜㅜ
4. 그리고 생각해보니 애초에 결과가 이상하게 나왔었겠어요. 저 의도대로라면 page를 매번 0으로 바꿔줘야하는데 그렇게 하지 않았습니다^^;;

이 부분 그냥 날리고 Pageable만 남기도록 하겠습니다.

2021-12-31 04:26 UTC, minseokLim commented on README.md
> +   * [X] **프로그래밍이 취미인 학생 혹은 주니어(0-2년)들이 다닌 병원 이름을 반환하고 user.id 기준으로 정렬하세요. (covid.id, hospital.name, user.Hobby, user.DevType, user.YearsCoding)**
1. (프로그래밍이 취미인 학생) 혹은 (주니어(0-2년)) 
2. 프로그래밍이 취미인 (학생 혹은 (주니어(0-2년))

이 둘 중에 뭘 말하는 걸까라는 고민을 하다가 2번을 택한 건데 1번인가보군요?

학생 타입도 좀 헷갈렸는데, student라는 컬럼이 있더라고요. 그래서 student like 'Yes%' 로 하려다가 '요구사항에 나온 저 컬럼들만 이용해야되는 건가? dev_type이 뭐지?'라는 생각에 살펴보니 dev_type에도 student라는 문자열이 포함되어있는 레코드가 있더라고요. 그래서 student like 'Yes%' 를 만족하는 레코드 수와 dev_type like '%student%'를 만족하는 수를 조회해보니 다르더군요...; 고민하다가 dev_type을 사용하였습니다. student like 'Yes%'로 변경하면 되겠죠?

2021-12-31 04:30 UTC, minseokLim commented on README.md
> +   * [X] **프로그래밍이 취미인 학생 혹은 주니어(0-2년)들이 다닌 병원 이름을 반환하고 user.id 기준으로 정렬하세요. (covid.id, hospital.name, user.Hobby, user.DevType, user.YearsCoding)**
그러고보니 진짜 제가 괜히 스크린샷으로 쿼리를 올렸나봅니다. 리뷰어님이 이전과 이후를 비교하시기 힘드시겠네요; 그래서 이전과 이후 둘 다 올립니다^^;;;;

2021-12-31 04:33 UTC, minseokLim commented on README.md
> +   * [X] **프로그래밍이 취미인 학생 혹은 주니어(0-2년)들이 다닌 병원 이름을 반환하고 user.id 기준으로 정렬하세요. (covid.id, hospital.name, user.Hobby, user.DevType, user.YearsCoding)**
그리고 student 컬럼에 인덱스를 걸 수도 있겠지만, 이미 목표 성능이 나왔기 때문에 추가하지 않았습니다.

2021-12-31 12:35 UTC, leeyohan93 commented on src/main/java/nextstep/subway/station/application/StationService.java
> +    private Specification<Station> computeSpecification(final Pageable pageable) {
페이징을 위해 많은 고민을 해주셨네요 ! 👍 
개인적으로 쿼리의 성능도 중요하지만 이야기해줏니 것처럼 spring data 에서 제공해주는 page 기능을 쓰지 못하게 되는 것은 아쉬운 부분 인 것 같아요 😂  페이징이란게 정말 많이 쓰이지만 생각보다 복잡하고 별도로 유지보수하고 관리하기는 힘든 부분 중 하나라고 생각이 드는 것 같아 수정해주신 방향이 더욱 좋게 느껴지네요 😄

2021-12-31 12:38 UTC, leeyohan93 commented on README.md
> +   * [X] **프로그래밍이 취미인 학생 혹은 주니어(0-2년)들이 다닌 병원 이름을 반환하고 user.id 기준으로 정렬하세요. (covid.id, hospital.name, user.Hobby, user.DevType, user.YearsCoding)**
네 맞습니다! student 테이블을 이용하시는 것이 좋을 것 같아요 :)
말씀해주신 것 처럼 이 부분은 미션을 진행하시는 분들이 헷갈리실 수 있는 부분이네요 !
조금 더 명확한 미션을 위해 건의드려볼게요 🙏

2021-12-31 12:40 UTC, leeyohan93 approved these changes
민석님 마지막 단계까지 잘 마무리 해주셨네요 💯
미션 완주 이후에도 이어지는 과정도 좋은 결과 있기를 기원하겠습니다 🙏
새해 복 많이 받으세요 😄

2021-12-31 12:40 UTC, merged

2021-12-31 12:41 UTC, minseokLim commented
> 민석님 마지막 단계까지 잘 마무리 해주셨네요 💯 미션 완주 이후에도 이어지는 과정도 좋은 결과 있기를 기원하겠습니다 🙏 새해 복 많이 받으세요 😄

네 감사합니다! 요한님도 새해 복 많이 받으세요! 😄