Step2 - 조회 성능 개선하기
next-step/infra-subway-performance pull request #154
Opened 2021-12-30 19:06 UTC by koola97620

안녕하세요! 리뷰어님!
안정적인 서비스 만들기 미션을 같이 진행하게 된 최재용 입니다! 잘부탁 드립니다!

이번 미션 진행할때 masterdb, slavedb 를 다른 인스턴스에 설치 후 진행하려고 했습니다.
그런데 masterdb 와 slavedb 간에 연결이 잘 안되는것 같더라고요 ㅠ
ping 을 날리면 패킷을 받기는 하는데, telnet 으로는 연결이 안되더라고요... 
(보안그룹에서 모든 포트를 허용하도록 바꿔도 안되네요)

그래서 어쩔수 없이 한 인스턴스에서 진행하려고 했는데 db에 database 가 없다고 에러가 났고
db 접속해서 database 만들고 spring.jpa.hibernate.ddl-auto=validate 설정을 create 로 바꾸고 한번 실행한 다음에
validate 로 다시 변경해주어 문제를 해결했습니다.

aws 에서 보안설정 바꿔보고 이것저것 시도하느라.
제가 미션을 제대로 진행한건지 헷갈리네요 ㅎㅎ;  
그래도 masterdb 에 생성된 데이터가 slavedb 로 복제 되는 것 까진 확인 했습니다!

우여곡절 많았지만 이것저것 설정도 만져보고 replication 과정을 직접 경험해보는 일을 할 수 있어서
재밌었습니다 ㅎㅎ  좋은 피드백 부탁드립니다!

감사합니다!

2021-12-31 07:53 UTC, kang-hyungu requested changes
재용님 피드백 한 가지 남겼습니다.
확인해보시고 리뷰 재요청주세요.

2021-12-31 07:53 UTC, kang-hyungu commented on src/main/java/nextstep/subway/station/domain/StationRepository.java
> +    Page<Station> findAll(Pageable pageable);
페이징 객체를 사용하면 성능에 이슈 없을까요?
페이징 적용한 api를 부하테스트를 실시해보시고 개선할 부분이 없을지 검토해보시기 바랍니다.

2021-12-31 18:23 UTC, koola97620 commented on src/main/java/nextstep/subway/station/domain/StationRepository.java
> +    Page<Station> findAll(Pageable pageable);
부하테스트 진행했습니다! 현재 DB 데이터가 극소량이라 테스트 결과가 적용전,후 큰 차이가 나지 않지만
데이터 양이 늘어날수록 차이는 더 커질거라 생각합니다!

2022-01-02 01:41 UTC, kang-hyungu approved these changes
재용님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리하겠습니다. 수고하셨습니다.

2022-01-02 01:41 UTC, merged