feat : step1 쿼리작성 수행
next-step/infra-subway-performance pull request #167
Opened 2022-03-27 14:53 UTC by rkdals213

미션2 진행하다 잘 안되서 해봤는데 생각보다 쉽지 않았습니다.

작성하다보니 완전 서브쿼리로만 작성이 되던데 이게 효율적인지는 모르겠습니다...
회사에서 다 이렇게 하더라구요 ㄷㄷ

2022-03-28 06:11 UTC, brainbackdoor requested changes
3주 차 1단계 미션 잘 진행하셨네요~
요구사항은 달성했지만, 다른 시도도 해볼만한 부분이 보여 피드백 남겨보았어요.

2022-03-28 12:19 UTC, rkdals213 commented on README.md
> +;
DEPENDENT SUBQUERY 를 제거해보았습니다.  처음에는 inner join을 사용해서 구현해봤는데 성능이 전혀 나오지 않아 from 절에서 조인을 시도해보니 성능이 기존 쿼리랑 비슷하게 나왔습니다

2022-03-29 12:12 UTC, brainbackdoor approved these changes
피드백 잘 반영해주셨네요! 👍🏻 
좀 더 개선할 포인트가 있지만 이번 단계는 여기서 머지할게요.
혹시 좀 더 도전해보고 싶으시다면 Comment 참고해서 개선해보세요.

2022-03-29 12:12 UTC, brainbackdoor commented on README.md
> +      group by 사원.사원번호, 사원.이름, 급여.연봉, 직급.직급명, 입출입구분, 지역
불필요한 정렬, 급여 테이블을 반복해서 스캔하는 부분 등을 제거할 수 있지 않을까요
<img width="946" alt="스크린샷 2022-03-29 오후 9 11 34" src="https://user-images.githubusercontent.com/29951288/160608452-45a5f592-70a2-415f-904f-2a740f5bc84a.png">

2022-03-29 12:12 UTC, merged