🚀 1단계 - 쿼리 최적화
next-step/infra-subway-performance pull request #171
Opened 2022-03-30 12:50 UTC by hk0305

안녕하세요~
2단계 미션이 생각보다 시간이 오래걸려 
3단계 미션 1 부터 PR 요청드립니다!

사원출입기록 테이블의 크기가 커서
모든 테이블을 한 번에 조인하기 보다
연봉 5위 안으로 들어가는 사원번호를 
연봉테이블에서 우선 조회하였습니다.

저희 집 PC 환경에서는 약 0.9초로 나옵니다.
미션 리뷰 부탁드립니다!

좋은 강의 해주셔서 정말 감사드립니다 ^_^ 👍

2022-03-30 20:15 UTC, brainbackdoor requested changes
1단계 미션 잘 진행해주셨네요! 👍🏻
다만, 응답값이 예시와 다른데요. 한번 확인해보시겠어요?

2022-04-03 08:34 UTC, hk0305 commented
안녕하세요~

* 응답값이 예시와 동일하도록 변경하였습니다~!
1. 직급 테이블에서 현재 관리자인 사람만 조회

2022-04-03 13:58 UTC, brainbackdoor approved these changes
1단계 미션 진행하느라 고생하셨어요! 👍🏻 
이번 단계는 여기서 머지할게요~ 2단계 진행해주세요~

2022-04-03 13:58 UTC, brainbackdoor commented on README.md
> +	SELECT DISTINCT PY.사원번호, MAX(PY.연봉) AS 연봉
DISTINCT 는 제거해도 되지 않을까요?

2022-04-03 13:58 UTC, brainbackdoor commented on README.md
> +  JOIN 사원 HR ON (HR.사원번호 = DRI.사원번호)
- 조인을 할 시에 필요한 컬럼만 반환하는 습관을 가져보셔요. 상황에 따라 커버링 인덱스를 적극적으로 활용할 수 있어요.

2022-04-03 13:58 UTC, brainbackdoor commented on README.md
> +  JOIN 사원 HR ON (HR.사원번호 = DRI.사원번호)
이번 미션은 사원출입시간 테이블과의 조인에 있어 드라이빙 테이블의 모수를 최소화하는 것이 목표예요.

2022-04-03 13:58 UTC, merged

2022-04-03 14:05 UTC, hk0305 commented on README.md
> +	SELECT DISTINCT PY.사원번호, MAX(PY.연봉) AS 연봉
확인했습니다!
제거하니 약 0.1초 줄었네요~!