Step3 쿼리 최적화
next-step/infra-subway-performance pull request #201
Opened 2022-05-05 15:09 UTC by jun731

안녕하세요 동규님!

쿼리를 두개 작성해보았는데요.
잘 된건지 모르겟네요 ㅠㅠ 

1. department.note = active  full index scan이 발생하는것
2. salary.annual_income의 order by desc , limit 으로 인한 tmp table, filesort 

이 두가지를 해결하지 못했습니다.
1번은 시간도 적게걸리고  full index scan이 발생할 수 밖에(?) 없는걸로 생각이들긴 하는데..
2번은 order by 는 임시테이블도 만들고 sort해서 시간이 좀 걸리더라고요.

이 두가지를 해결하기 위해서 인덱스 말고 다른 방법이 있을까요?
힌트 부탁드리겠습니다 :)

2022-05-06 13:35 UTC, brainbackdoor requested changes
3단계 미션 진행하느라 고생하셨어요~ 
미션 요구사항이 맞지 않는데요. 한번 확인 부탁드려요.
그리고 현재 쿼리 기준으로 추가로 몇가지 피드백 남겨두었는데요. 참고 바래요~ 👋🏻

2022-05-06 13:35 UTC, brainbackdoor commented on README.md
> +where r.record_symbol = 'o' and p.end_date > now();
만약 동일한 결과를 내야 하는 요구사항이라면, 저라면 아래와 같이 작성할듯해요.
쿼리를 왜 아래와 같이 바꾸었는지는 실행계획과 현재 인덱스를 보면서 직접 생각해보시는게 도움될듯해요.
그리고 추가로 (annual_income, id) 복합 인덱스를 생성할듯해요. 
테스트해보니 인라인뷰에서 정렬비용이 상당하기 때문입니다. 

```sql
select salary_top_5.employee_id, e.last_name, e.first_name, p.position_name, r.time, r.region, r.record_symbol
from (
   select ed.employee_id, department_id
    FROM (SELECT employee_id,department_id  from tuning.employee_department ) as ed 
    join (SELECT id, annual_income FROM tuning.salary WHERE end_date > now())as s on ed.employee_id = s.id
    order by s.annual_income desc limit 5
) as salary_top_5
inner join (SELECT id, note FROM tuning.department WHERE note = 'active') as d on salary_top_5.department_id = d.id
inner join tuning.record as r on salary_top_5.employee_id = r.employee_id
inner join tuning.employee as e on salary_top_5.employee_id = e.id
inner join tuning.position as p on salary_top_5.employee_id = p.id
where r.record_symbol = 'o' and p.end_date > now()
```

관건은 드라이빙 테이블이 되는 inline view 탐색비용을 어떻게 줄일지 입니다.

### 개선 전

<img width="1301" alt="스크린샷 2022-05-06 오후 10 33 01" src="https://user-images.githubusercontent.com/29951288/167141916-9e48e07e-baa8-42f6-bb9f-6a68f9a40f43.png">


### 개선 후


<img width="1125" alt="스크린샷 2022-05-06 오후 10 31 21" src="https://user-images.githubusercontent.com/29951288/167141479-6f292db1-93d4-49c2-8219-cd0694946fe8.png">

2022-05-06 14:40 UTC, jun731 commented
@brainbackdoor  리뷰어님 주신 멘트 참고해서 https://github.com/next-step/infra-subway-performance/pull/201/commits/65686c898ee7557be0e2729bc5d3817dfc057509 sql을 수정해보았습니다 

sql다루는게 어렵네요 ㅠㅠ

2022-05-06 14:42 UTC, jun731 commented on README.md
> +where r.record_symbol = 'o' and p.end_date > now();
동규님.. 인라인뷰가 서브쿼리가 FROM 절에서 안에서 사용되는 경우, 해당 서브쿼리를 말씀주시는거 맞..죠?

2022-05-06 14:42 UTC, jun731 commented on README.md
> +) as salary_top_5
억!!
그렇지않아도 step4하면서 겪었습니다! 감사합니다

2022-05-06 14:42 UTC, jun731 commented on README.md
> +where r.record_symbol = 'o' and p.end_date > now();
ㅠㅠ 고쳐보겠습니다

2022-05-06 14:49 UTC, jun731 commented on README.md
> +where r.record_symbol = 'o' and p.end_date > now();
동규님 말씀주신것처럼 from절 그러니 드라이빙테이블의 결과를 줄인게 효과적인듯한데 
밑에 주신 그림 즉 실행계획이 아직.. 눈에 잘 들어오지않아서 드리는 질문이긴한데요.

인라인뷰에서 정렬비용이 상당하다는 곳이 '개선전'의 rows 41392로 되엉쓴ㄴ 줄과 그 위의 줄이 문제인걸까요?

2022-05-07 03:17 UTC, brainbackdoor commented on README.md
> +where r.record_symbol = 'o' and p.end_date > now();
넵넵 맞습니다. derived 로 묶여 있는게 인라인뷰라고 보시면 되요.
visualize 로 봤을 떄 별도 영역으로 구분되어 있을거에요.

원래 작성했던 쿼리가 느린 이유는, 원래 쿼리 중 아래 부분에서 오래 걸리기 때문이에요.

```sql
    select ed.employee_id from tuning.employee_department as ed
    inner join tuning.department as d on ed.department_id = d.id
    inner join tuning.salary as s on ed.employee_id = s.id
    where d.note = 'active' and ed.end_date > now() and s.end_date > now()
    order by s.annual_income desc limit 5
```

---

넵넵 맞아요. nested loop 로 돌다보니 많은 줄을 중첩해서 탐색하면 굉장히 느려져요.
위 케이스에선 왜 저런 부분들이 발생하는지 보다보니 정렬하는 부분(order by s.annual_income) 때문이더라구요.
그래서 소팅연산을 없애려면 어떻게 할지 한번 고민해봤어요.
그 외에도 end_date > now() 조건이 반드시 필요한가도 한번 생각해보세요. 
그렇지 않다면 모든 경우에 넣어주는 것이 반드시 좋은가, 아니라면 왜일까도 생각해보시면 좋을듯해요.

2022-05-07 11:40 UTC, brainbackdoor approved these changes
3단계 미션 진행하느라 고생하셨어요~ 
추가로 개선할 포인트가 보여 피드백 남겨요.
이번 단계는 여기서 머지할게요~

2022-05-07 11:40 UTC, brainbackdoor commented on README.md
> +WHERE position.end_date > now();
이 쿼리도 서브쿼리가 불필요하게 중첩되어 있어요.

### 개선전
<img width="1226" alt="스크린샷 2022-05-07 오후 8 37 16" src="https://user-images.githubusercontent.com/29951288/167252576-4e8cbd00-2b44-4471-b15a-448a553e7380.png">



### 개선후
<img width="1285" alt="스크린샷 2022-05-07 오후 8 35 45" src="https://user-images.githubusercontent.com/29951288/167252538-c48fe97d-50f8-405e-a0c6-36b135aeeb78.png">

record 테이블의 rows 가 많은데요. 이를 서브쿼리 안에 두기 보다는 드리븐 테이블에 두고 인라인 뷰의 결과를 줄여보는건 어떨까요

2022-05-07 11:40 UTC, merged