[3주차] 1단계 & 2단계 제출합니다.
next-step/infra-subway-performance pull request #206
Opened 2022-05-07 14:06 UTC by loop-study

안녕하세요 박현철입니다.
진행중 로드밸런스에서 막혀서 도움받고자 Pr 요청드립니다.

**1단계**
- Redis & 캐쉬를 적용할 때 순환참조를 겪었습니다. 처음에는 단순히 JPA 문제인줄 알고 삽질했다가 뒤늦게 Line, Station, Path 모두 캐쉬를 적용했던게 문제로 알게되었는데 Redis & 캐쉬를 적용할 때 주의해야할 점이 궁금합니다.

**2단계**
- 인증서를 맞게 가져왓는지 궁금합니다.
https://ap-northeast-2.console.aws.amazon.com/acm/home?region=ap-northeast-2#/certificates/list

- ALB에서 인증서 적용을 맞게 했는지 궁금합니다.
https://ap-northeast-2.console.aws.amazon.com/ec2/v2/home?region=ap-northeast-2#LoadBalancers:sort=loadBalancerName

- DNS 설정에서 CNAME만 뺴고 다 지웠다가 다시 TXT 설정하려는데 dig -t txt _acme-challenge.example.com +short 명령어가 안되고 있습니다. 다른 방법이 있는지 궁금합니다.
![image](https://user-images.githubusercontent.com/19161176/167257721-0cf087fd-c8d1-4aef-a6fd-d02c98c32d4d.png)

확인 부탁드립니다.
감사합니다.

2022-05-08 05:24 UTC, brainbackdoor commented
안녕하세요. 
1. 데이터 캐시는 가급적 응답 결과를 캐싱해주세요. 그리고 캐시를 걸 때 어느 시점에 Evict해야 하는지를 잘 살펴보아야 합니다. 그렇지 않으면 멱등성을 보장하지 못하는 경우가 발생할 수 있습니다.
2. 인증서는 잘 가져왔지만, ALB 에 ACM 설정이 안되어 있어요. 프로토콜을 https 로 설정하면 ACM  설정이 가능합니다.
<img width="841" alt="스크린샷 2022-05-08 오후 1 50 59" src="https://user-images.githubusercontent.com/29951288/167282721-dc376bb8-c751-4609-bfa1-5dff71df3d9d.png">

3. TXT 는 처음에 lets encrypt 인증할 때만 사용되고 이후에는 사용되지 않아요. 제거했다면 다시 등록할 방법은 없어요. 만약 다시 등록하고 싶다면, 다시 인증받으면서 값을 설정하셔야 해요. 

4. was 가 공인 IP 가 없어서 awscli 등을 받아오지 못하고 있어요. 그래서 정상적으로 배포 스크립트를 못받아와서 was 를 띄우지 못하고 있네요. launch template 에서 공인 ip 를 할당하도록 설정하셔야 해요.

2022-05-08 05:28 UTC, brainbackdoor requested changes
2단계 launch template 으로 인스턴스 띄우는 중에 비정상 구동되고 있네요.
관련해서 Comment 남겨두었어요~ 
즐거운 주일 보내세요~ 👋🏻

2022-05-08 05:28 UTC, brainbackdoor commented on README.md
> +| 비교    | -1.8초  | -1.7초  | -1.2초  | -1.7초  | +60 밀리초  | +0.004  |
👍🏻

2022-05-08 05:28 UTC, brainbackdoor commented on 1단계_부하테스트/현재_load_paths_log.txt
> +       { expected_response:true }...: avg=3.9ms    min=1.92ms  med=3.29ms  max=36.06ms p(90)=5.87ms   p(95)=7.78ms
많은 부분 개선되었군요! 👍🏻

2022-05-09 12:05 UTC, loop-study commented
수정하여 다시 요청드립니다!
확인 부탁드립니다!

2022-05-09 14:06 UTC, brainbackdoor approved these changes
2단계 미션 진행 잘해주셨네요! 👍🏻 
몇가지 피드백 남겨두긴 했는데요. 
이번 단계에서 목표한 바는 달성하셨다고 생각하여 여기서 머지할게요~
좋은 밤 보내세요! 👋🏻

2022-05-09 14:06 UTC, brainbackdoor commented on README.md
> +   https://ap-northeast-2.console.aws.amazon.com/ec2/v2/home?region=ap-northeast-2#LaunchTemplateDetails:launchTemplateId=lt-0206013aee338803a
<img width="1161" alt="스크린샷 2022-05-09 오후 11 02 42" src="https://user-images.githubusercontent.com/29951288/167427349-d37c0112-c928-457a-9487-f87922917846.png">

음.. 현재 캐싱 정책이 잘못 적용되었나보네요. 테스트 중이신가봐요.

2022-05-09 14:06 UTC, merged

2022-05-10 04:32 UTC, loop-study commented on README.md
> +   https://ap-northeast-2.console.aws.amazon.com/ec2/v2/home?region=ap-northeast-2#LaunchTemplateDetails:launchTemplateId=lt-0206013aee338803a
이것저것 바꿔보고 있습니다. 🙈