Step2 조회 성능 개선하기
next-step/infra-subway-performance pull request #22
Opened 2021-07-06 15:58 UTC by etff

안녕하세요 리뷰어님. step2 단계를 진행하여 PR 보냅니다.

이번에 DB 이중화를 해보았는데요. AWS 에서 제공하는(<del>유료로</del>)외에 
직접 DB 이중화를 해보니 재미있었습니다.

페이징 처리에서 pagable은 어느 방법이 좋은 방법인지 고민이네요. 
Pagable로 받지 않고 page와 size만 받고, 컨트롤러에서 Pageable 객체를 만들어 넘기는 방법도 있는 것으로 아는데
혹시 좋은 팁이 있을까요?

2021-07-07 11:48 UTC, tearight requested changes
예제 쿼리 성능을 개선하신 부분에서 조금 더 개선이 되면 좋을 것 같습니다.
코멘트 확인 부탁드릴게요.

2021-07-07 11:48 UTC, tearight commented on asset/sql/problem1/sql.md
> +     )t2;
유니온절을 제거하여 임시테이블을 한번만 정의하면 어떨까요 ?

2021-07-07 11:48 UTC, tearight commented on asset/sql/problem2/sql.md
> +```
쿼리는 문제가 없지만 실제 데이터 양이 많은 경우에 비용이 많이 발생하니 페이징 쿼리가 필요해보입니다.

2021-07-07 11:48 UTC, tearight commented on asset/sql/problem3/sql3.md
> +```
인덱스 생성시 사용되는 컬럼의 순서를 바꾸면 인덱스 참조 성능이 개선될 것 같네요.
https://jojoldu.tistory.com/243
이 포스트를 확인해주시면 좋을 것 같아요.

2021-07-07 11:48 UTC, tearight commented on asset/sql/problem4/sql4.md
> +```
where 절에 사용되는 조건을 확인하셔서 인덱스를 추가해주시면 성능 개선이 될 것으로 보입니다.

2021-07-07 11:48 UTC, tearight commented on asset/sql/problem5/sql5.md
> +group by p.exercise;
where 절 뿐만 아니라 group by 에 사용되는 것도 인덱스를 하면 인덱스에 의해서 정렬을 하게 되어 정렬 성능이 좋아집니다.

2021-07-07 11:55 UTC, tearight commented
> * 이번에 DB 이중화를 해보았는데요. AWS 에서 제공하는(~유료로~)외에
>   직접 DB 이중화를 해보니 재미있었습니다. 거기에 DB의 기능을 나누어서 작업한다는 것도 신선했습니다.
>   물론 연습이니 이렇게 할 수 있지만, 서비스가 커졌을때 비용이 걱정이 드네요. 현업에서 이렇게 쓰이는 사례가 많나요?

대규모 서비스에서는 [서비스 품질 > 서버 비용] 이 성립합니다.
시스템에 자그마한 병목이 발생하면 큰 장애로 커질수도 있어서 많은 회사에서 리스크를 줄이는 방향으로 인프라를 구성합니다.
RDBMS 는 구조상 1개의 writer 와 여러개의 reader 를 갖는데요, 요청 규모가 커지면 커질수록 writer 가 갖는 부하가 커지고, 인스턴스를 스케일업 하는 것으로 병목/부하를 단순하게 해결할 수 없기 때문에 writer 와 reader 가 나누어서 요청을 처리하도록 설계되어야 합니다.

> * 페이징 처리에서 pagable은 어느 방법이 좋은 방법인지 고민이네요.
>   Pagable로 받지 않고 컨트롤러에서 page와 size만 받고 Pageable 객체를 만들어
>   서버스로 넘기는 방법도 있는 것으로 아는데 혼란스럽습니다. 혹시 좋은 팁이 있을까요?

Pageable 은 스프링에서 지원하는 인터페이스로써 저는 서비스로 넘겨도 괜찮다고 생각합니다.
오히려 각 요청마다 Pageable 의 요소들을 커스터마이징하면 일관성 있는 테스트가 힘들어져서 유지보수 비용이 많이 발생한다고 생각이 드네요.

2021-07-07 14:06 UTC, etff commented on asset/sql/problem5/sql5.md
> +group by p.exercise;
문제의 요구사항이 운동횟수별로 집계를 해야하는데요. excercise의 항목이 text여서 인덱스 설정을 걸 수가 없습니다.
> see also https://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length

2021-07-07 16:33 UTC, etff commented on asset/sql/problem2/sql.md
> +```
페이징을 적용했습니다

2021-07-07 16:34 UTC, etff commented on asset/sql/problem3/sql3.md
> +```
카드너리티를 고려해서 인덱스를 수정했습니다. 좋은 포스팅 공유 감사합니다!!

2021-07-07 16:37 UTC, etff commented on asset/sql/problem4/sql4.md
> +```
country를 인덱스를 추가했습니다. Hospital 테이블의 name이 text 속성이네요

2021-07-07 16:37 UTC, etff commented on asset/sql/problem1/sql.md
> +     )t2;
쿼리가 너무 비효율적인 것같아 수정했습니다.

2021-07-08 15:14 UTC, tearight commented on asset/sql/problem4/sql4.md
> +```
그렇군요, varchar 인줄 알았네요. 😂
개선이 어려운 포인트로 확인하였습니다.

2021-07-08 15:15 UTC, tearight commented on asset/sql/problem3/sql3.md
> +create index idx_programmer on programmer (years_coding, hobby, student);
👍

2021-07-08 15:16 UTC, tearight approved these changes
피드백을 잘 반영해주셨습니다. 👍
머지하겠습니다. 다음 미션도 화이팅입니다!

2021-07-08 15:16 UTC, merged

2021-07-08 15:21 UTC, etff commented
> 피드백을 잘 반영해주셨습니다. 👍
> 머지하겠습니다. 다음 미션도 화이팅입니다!

감사합니다. 이번 미션을 하면서 인덱스를 많이 고민하게 되었습니다.
인덱스를 어떻게 하면 효율적으로 걸 수 있을지, 실행계획을 살펴보고
카디너리티는 어떤지 효율적인 쿼리는 무엇인지 연습을 해보았습니다. 

미션을 진행하며 답변 달아주신 내용도 좋은 내용이라 기억에 많이 남내요 👍