Step1 - 화면 응답 개선하기
next-step/infra-subway-performance pull request #276
Opened 2022-07-03 08:51 UTC by Sung-jin

안녕하세요.
마지막 실습 과제네요.
전체적인 과정을 진행하면서 정말 많은 것들을 배우고 생각할 수 있던 의미 깊은 시간이었던 것 같습니다.

리뷰어님도 8주간 고생 정말 많으셨습니다. 그리고 이번 리뷰도 잘 부탁드립니다. 😊
안정적인 서비스 만들기 실습을 통해 많은 것을 배우고 생각할 수 있도록 진행하겠습니다.
리뷰어님도 리뷰를 통해 한층 발전할 수 있는 기회가 되었으면 좋겠습니다 👍

2022-07-03 09:00 UTC, Sung-jin commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
>      public void createFavorite(LoginMember loginMember, FavoriteRequest request) {
개인적으로 LoginMember 를 찾는 `AuthService` 의 `findMemberByToken -> memberRepository.findByEmail`  를 캐싱하는 형태도 괜찮을 것 같습니다.

유저 권한이 필요한 기능에서 로그인된 사용자의 정보는 거의 변경되지 않을테니, 해당 결과를 캐싱한다면 유저 권한이 필요한 모든 곳에서 유저에 대한 정보를 db 에 접근하지 않고 처리할 수 있을 것 같습니다.

그런데, 생각해보니 spring security 를 사용한다면 context 에 저장된 유저 정보로 접근이 가능할 것 같네요.

2022-07-03 22:56 UTC, parkeeseul requested changes
안녕하세요 안정적인 서비스 만들기 미션을 함께 하게 된 박이슬 입니다.
1단계 미션 잘 진행해 주셨네요! 👍 
몇 가지 코멘트와 질문주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드립니다.
함께 이번 미션 잘 진행해 보아요 화이팅 입니다 🔥

2022-07-04 03:51 UTC, Sung-jin commented on src/main/java/nextstep/subway/common/CacheConfig.java
> +//}
확인을 위해 주석을 처리 해 놓고 그대로 커밋을 했네요...

리뷰 요청 후 다시 한번 확인을 했어야 했는데, 꼼꼼하지 못했던 것 같습니다.

2022-07-04 04:02 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    @Cacheable(value = "allLine", unless = "#result.isEmpty()")
리뷰해주신 파일은 LineService 인데, MapService 의 `findPath` 메소드를 캐싱한 부분을 말씀하시는게 맞을까요?

맞다면,
서비스 특성상 지하철 `지하철 노선`/`경로 검색` 이 주 서비스이며, 해당 데이터들은 도메인 특성상 추가/수정/삭제의 빈도가 낮고 조회의 빈도가 높다고 생각됩니다.

경로 조회의 경우에도 시작점과 끝점이 같다면 노선의 정보가 변경되거나 지하철간의 거리가 변경되는 등의 데이터 변경이 일어나지 않는다면 같은 결과가 반환될 것이므로 path 에 대해서도 캐시 설정을 추가하였습니다.

2022-07-04 04:04 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    @Cacheable(value = "allLine", unless = "#result.isEmpty()")
하지만 atdd-subway-service 과정과 요금이 추가가되고, 나이별 요금이 달라진다는 요구사항이 추가된다면 캐싱 처리방법을 변경하거나 캐싱 처리를 제거하는 등의 변경사항은 있을 것 같습니다.

지금은 시작점과 끝점을 바탕으로 경로를 탐색한다 라는 기능만 존재하여, 캐싱을 처리를 했습니다.

2022-07-04 04:09 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    )
생성 요청 객체에는 구분자(id) 가 없고, 생성된 결과에 해당 데이터에 대한 구분자가 생성되므로 `result.id` 로 구분 키를 설정했었습니다.

> Line을 조회할 떄가 아닌 save 할때 lineResponse 을 캐싱 하는 이유가 있으신가요? thinking

위 리뷰 내용과 같이 다시 생각해보니, 해당 부분은 캐싱할 필요가 없어서 제거하겠습니다.

2022-07-04 04:14 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            cacheable = { @Cacheable(value = "lineResponse", key = "#result.id") },
ui 에서 조회 요청을 하는 `findLineResponseById` 의 결과가 `saveLine` 의 결과와 같기 때문에, 새로 생성되자마자 노선에 대한 캐싱을 추가하였습니다.

리뷰해주신 내용을 바탕으로 생각해보니.. 오버 스펙인것 같기도 하네요.

캐싱을 처리한다는 의미는 오래 걸리거나 반복 조회되는 데이터를 빠르게 조회할 수 있게 하기 위함인데,
조회 요청이 오지도 않은 생성된 객체를 바로 캐싱하니 해당 데이터가 캐시로써 사용된다는 보장이 없을 것 같네요.

해당 리뷰가 혹시 이런 의도로 말씀해 주신게 맞을까요?

2022-07-05 09:28 UTC, parkeeseul reviewed
피드백 잘 반영해 주셨네요! 
몇 가지 코멘트 남겨두었으니 확인 부탁드리고
다음 단계 진행해 주세요!
화이팅 입니다 🔥

2022-07-05 09:28 UTC, parkeeseul commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    )
제가 알기로는 @CachePut 에서는 가능하지만 @Cacheable 에서는 지원하지 않는 것으로 알고 있는데요
혹시 해당 부분 테스트가 진행된 부분이실까요? 😄 

https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache-spel-context

2022-07-05 09:28 UTC, merged

2022-07-07 10:43 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    @Cacheable(value = "allLine", unless = "#result.isEmpty()")
음... 말씀의 뜻을 이해하지 못했습니다.

findLines 의 경우에는 노선 목록이고, findPath 는 경로찾기의 결과들에 대한 캐싱 의도로 각각 캐싱을 처리했습니다.

노선의 경우에는 전체 노선을 사용자가 별도로 조회를 할 수 있고, 경로의 경우에는 특정 역간의 최단 거리를 조회하는 순간에 해당 값을 찾아내는 결과를 캐싱한 것이므로 다르다고 생각하였습니다.

> 경로 조회의 경우에도 시작점과 끝점이 같다면 노선의 정보가 변경되거나 지하철간의 거리가 변경되는 등의 데이터 변경이 일어나지 않는다면 같은 결과가 반환될 것이므로 path 에 대해서도 캐시 설정을 추가하였습니다.

위와 같은 이유로 전체 노선 조회는 조회용이므로 별도로 캐싱을 처리하였고, 경로 탐색의 경우에는 관련된 데이터가 변경되지 않는 이상 같은 결과가 나오므로, 경로에 대해 캐싱 처리를 했습니다.

2022-07-07 10:43 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    @Cacheable(value = "allLine", unless = "#result.isEmpty()")
결론적으로 `MapService.findPath()` 와 `lineService.findLines()` 는 용도가 다르고 생성되는 시점이 다르기 때문에 별도로 캐싱 처리를 했습니다.

2022-07-07 10:45 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    )
아..! 감사합니다.

미숙한 상태로 구현을 해버린거 같아서 부끄럽네요..

그리고 테스트의 경우... redisConfig 를 주석한 상태로 레디스가 설정된 줄 알고 테스트를 했었던 것 같습니다.
실제 데이터가 잘 올라갔는지 확인까지 했어야 했는데.. 꼼꼼하지 못했네요.

2022-07-07 10:48 UTC, Sung-jin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            cacheable = { @Cacheable(value = "lineResponse", key = "#result.id") },
넵, 전체적으로 여러가지를 생각하고 테스트를 하다 보니, 저장하는 데이터의 캐싱은 하지 않는게 좋을 것 같다는 결론을 내렸습니다.

저장을 한다고 해당 데이터가 사용된다는 보장이 없기 때문에 저장 시점에 해당 데이터를 캐싱하지 않는게 좋다고 생각합니다.
그리고 테스트를 하다보니, 이전 코드에 엔티티도 캐싱을 하려고 했었는데 detach 문제 등등 많은 부분이 문제가 되더라고요.

결론적으로 조회 데이터에 대해서만 캐싱을 하며, 사용성이나 사용 빈도 등을 고려해서 캐싱을 해야 한다.
그리고 데이터 무결성 문제도 존재하므로 목적에 따라 ttl 등을 고려해야 한다.

이렇게 결론을 내렸습니다.