Step1: 화면 응답 개선하기
next-step/infra-subway-performance pull request #302
Opened 2022-07-04 17:34 UTC by lakey001

순호 리뷰어님, 안녕하세요!
DM으로 먼저 인사드렸지만 안정적인 서비스 만들기 미션 함께 진행하게된 이수연입니다. ^^
조언해주신대로 webserver를 개선시 PageSpeed 점수가 개선이 되고, WAS에 Cache까지 적용하고 나니 K6테스트 결과가 개선된 것을 확인할 수 있었습니다!
Redis Cache를 처음 사용해보는 부분이어서 직렬화 부분에서 조금 헤매었지만, 적용하고 나니 확실히 성능이 좋아져서 보람있는것 같습니다 ㅎㅎ

마지막 미션동안 잘부탁드리며, 시간되실 때 확인 부탁드립니다. 감사합니다! 😄

2022-07-05 15:01 UTC, oper912 requested changes
수연님 안녕하세요 :)
안정적인 서비스 만들기 미션 함께 하게된 권순호입니다 🙂
1단계 진행 잘해주셨네요 👍
다만 몇가지 코멘트 남긴것들이 있는데요 확인후에 리뷰 재요청 부탁드립니다!

2022-07-05 15:01 UTC, oper912 commented on src/main/java/nextstep/subway/station/application/StationService.java
> +    @CacheEvict(cacheNames = "allStation")
또는 @Cacheable(value = "allStation") 시에 key값은 어떻게 저장되는지도 같이 확인해보시면 좋을 것 같아요

2022-07-05 16:08 UTC, lakey001 commented on src/main/java/nextstep/subway/common/CacheConfig.java
> +@Profile("prod")
좋은 팁 감사합니다! 반영하였습니다 :)

2022-07-05 16:10 UTC, lakey001 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    @Cacheable(value = "allLine")
unless 옵션을 미처 몰랐네요 😅 바로 적용하였습니다!
Transaction도 필요한 readOnly=true를 default로 하고, DB 변경이 필요한 곳에만 @Transactional 애노테이션 추가하였습니다!

2022-07-05 16:14 UTC, lakey001 commented on src/main/java/nextstep/subway/station/application/StationService.java
> +    @CacheEvict(cacheNames = "allStation")
전반적으로 Cache 사용이 어설펐네요 😅 
모든 캐시가 삭제될 수 있도록 해당부분 추가하였습니다!
@Cacheable, @CacheEvict 사용 시 key값은 기본적으로 파라미터 값으로 적용되고, 파라미터가 없다면 '0'이 key로 사용된다는 부분 확인하였습니다. 감사합니다 :)

2022-07-05 16:14 UTC, lakey001 commented on src/main/resources/application-prod.properties
> +spring.redis.port=6379
local, test profile 추가하였습니다 😄

2022-07-06 00:25 UTC, oper912 approved these changes
피드백 반영 잘해주셨네요 👍
머지하도록 하겠습니다 다음 단계 진행해주세요~ 💪

2022-07-06 00:25 UTC, merged