Step1 - 화면 응답 개선하기
next-step/infra-subway-performance pull request #323
Opened 2022-07-06 01:10 UTC by songsimo

안녕하세요. 🙇‍♂️ 처음 인사드려요.

화면 응답 개선하기 과제 완료하여 PR 드립니다.
이번 미션 동안 잘 부탁드립니다, 리뷰어님.

+
과제를 진행하고 궁금한 사항이 생겼어요. stress 테스트를 해보니 개선 전이 개선 후보다
http_req_duration 수치가 좋게 나왔는데 제가 개선을 잘 못 한걸까요?

2022-07-06 14:02 UTC, chae-yh requested changes
안녕하세요! 리뷰를 맡은 채영훈입니다. 반갑습니다 : )
마지막 인프라 미션인데, 전체적으로 환경 구성 및 테스트 잘 해주셨습니다 👍 
다만 조금만 더 고민해주시면 좋을만한 내용이 있어 코멘트 드렸으니 확인 부탁드립니다!

감사합니다 : )

2022-07-07 11:32 UTC, songsimo commented on src/main/java/nextstep/subway/line/application/LineService.java
>      public LineResponse saveLine(LineRequest request) {
네... 맞네요 수정하겠습니다 🙇‍♂🙇‍♂

2022-07-07 11:55 UTC, songsimo commented on src/main/resources/application-prod.properties
> +spring.redis.host=localhost
말씀하시는 부분은 제가 아직 기초적인 부분을 몰라 이해하지 못하고 있어요 🤔 일단 참고만하고 추가적으로 고민하겠습니다.

해당 부분 이야기 해주셔서 감사합니다!!! 모르고 지나쳤을거에요...

2022-07-07 12:01 UTC, songsimo commented on src/main/java/nextstep/subway/map/application/MapService.java
> +    @Cacheable(value = "path", key = "{#source, #target}")
네! 감사합니다. 인프라에 직접적으로 관여해본 적이 없어 이러한 내용들이 다 생소하네요. 앞으로도 계속 고민해보겠습니다 = )

2022-07-07 15:37 UTC, merged