4단계 - 인덱스 설계
next-step/infra-subway-performance pull request #374
Opened 2022-07-08 16:20 UTC by handh0413

석홍 리뷰어님 안녕하세요!
미션 4단계에 대한 PR 입니다.

시간 여유 되실 때 리뷰 부탁드립니다.
감사합니다! 🔥

2022-07-09 06:02 UTC, seokhongkim requested changes
동희님, 4단계 인덱스 설계 미션 잘 진행해주셨습니다. 👍 
쿼리 실행 플랜과 실행 시간을 확인했을 때, 미션 목표를 달성하신 것으로 보이네요.
조금 더 자세한 확인이 가능하도록 인덱스 설정도 PR에 추가 부탁드립니다. :)

2022-07-09 06:02 UTC, seokhongkim commented on README.md
>  1. 인덱스 적용해보기 실습을 진행해본 과정을 공유해주세요
테이블 별로 설정하신 인덱스 설정도 첨부 부탁드려요!

2022-07-09 10:52 UTC, handh0413 commented on README.md
>  1. 인덱스 적용해보기 실습을 진행해본 과정을 공유해주세요
미션의 중요 포인트 중에 하나가 인덱스 정보인데 제가 빼먹었네요.. 😭
다시 리뷰 요청 드릴게요. 시간 여유 되실 때 리뷰 부탁드립니다!

2022-07-09 14:34 UTC, seokhongkim requested changes
동희님, 인덱스 참고하여 4단계 미션 잘 진행하신 것 확인했습니다. 👍 
대부분 잘 진행해주셨는데, 조금 수정이 필요한 부분이 있어서 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +| covid      | id_UNIQUE              | id
PK 설정으로 유니크 인덱스를 설정하지 않아도 될텐데, 따로 설정하신 이유가 있을까요?

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +| hospital   | idx_hospital_name      | name
이 인덱스도 위의 `name_UNIQUE` 와 중복으로 보이네요!

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +| covid      | id_UNIQUE              | id
unique index 와 index 의 네이밍 규칙이 unique 가 붙는 것 외에 테이블명이 포함되는지 여부, id vs idx 로 다른데요.
다른 이유가 있을까요? :)

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +    - 국가별 프로그래머 비율 확인
개발을 취미로 하는지에 따른 비율이 나와야 하는데, 국가별 프로그래머 비율을 계산해 주셨네요!

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +inner join member m on m.id = c.member_id;
`프로그래머별` 이므로, `member` 테이블이 아닌 `programmer` 테이블과 조인이 필요하지 않을까요?

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +select c.id, h.name, p.hobby, p.dev_type, p.years_coding
인덱스 설정 잘 되었고, 쿼리 실행 결과와 시간 모두 미션 요구사항 만족하는 것 확인했습니다. 👍

참고로, 이 쿼리를 mysql workbench 에서 실행하신 경우 limit 조건이 자동으로 생성되었을 것으로 보입니다.
실제로 전체 데이터를 조회하면 시간이 오래 소요되는데, 미션의 목표 시간은 limit 기준으로 정해진 것으로 보이네요. :)
수정하셔야 하는 부분은 아니고, 혹시 놓치셨다면 알고 계시면 도움이 될 것 같아서 코멘트로만 남겨 놓습니다.

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +from (select id from member where age between 20 and 29) m
**1번, 2번 쿼리를 먼저 수정해주시고, 아래 내용은 여유가 되시면 선택적으로 참고 부탁드립니다.**

1. 서브 쿼리를 사용하지 않고, join 만 사용해도 동일한 결과를 만드실 수 있을 것 같아요.
2. 실행 계획을 보시면 프로그래머 테이블에서 PK를 사용한 후 `country` 에 대한 필터링은 `Extra` 절을 보시면 `Using where` 로 되어 있을 것으로 보입니다. `use index` 를 이용하여 `country` 인덱스를 사용하도록 설정하시면 `Using index` 로 변경되어 커버링 인덱스를 사용할 수 있습니다. 수정한 후 쿼리 실행 속도를 한번 확인해보셔도 좋겠습니다. :)
```sql
select c.stay, count(m.id)
from member m
         inner join programmer p  use index (idx_programmer_country) on m.id = p.id and p.country = 'india'
         inner join covid c on c.programmer_id = p.id
         inner join hospital h on h.id = c.hospital_id and name = '서울대병원'
where age between 20 and 29
group by stay
```

2022-07-09 14:34 UTC, seokhongkim commented on README.md
> +- [x] 서울대병원에 다닌 30대 환자들을 운동 횟수별로 집계하세요. (user.Exercise)
인덱스 설정 잘 되었고, 쿼리 실행 결과와 시간 모두 미션 요구사항 만족하는 것 확인했습니다. 👍

2022-07-09 15:12 UTC, handh0413 commented on README.md
> +| covid      | id_UNIQUE              | id
수업 시간에 이런 패턴으로 진행하시길래 방법에 대해서 크게 고민하지 못하고 따라했던 것 같습니다.
PK가 이미 유일성을 보장해 주므로 중복 컬럼에 대한 UNIQUE는 없애는 방향으로 다시 도전해보겠습니다!

2022-07-09 15:31 UTC, handh0413 commented on README.md
> +    - 국가별 프로그래머 비율 확인
링크를 클릭해보니 전체에 대한 여러 선택지를 퍼센티지 형태로 보여주고 있어서 비슷한 패턴으로
출력하면 되는 것으로 오해를 했던 것 같습니다.. 😢 쿼리 확인해서 수정하겠습니다!

2022-07-09 16:11 UTC, handh0413 commented on README.md
> +| hospital   | idx_hospital_name      | name
UNIQUE 부분은 기존에 추가된 테이블의 PK와 겹치는 부분이 있으므로 제거하도록 하겠습니다

2022-07-09 16:11 UTC, handh0413 commented on README.md
> +| covid      | id_UNIQUE              | id
MySQL Workbench에서 기본적으로 설정해 놓은 값을 그대로 사용하다보니 그렇게 되었습니다...
다음번엔 사용하는 Unique Key 관련하여 uk_tablename_columname 패턴으로 현재 인덱스 네이밍과
비슷한 패턴으로 만들어 질 수 있도록 개선해봐야 할 것 같습니다

2022-07-09 16:16 UTC, handh0413 commented on README.md
> +select c.id, h.name, p.hobby, p.dev_type, p.years_coding
넵 확인해주셔서 감사합니다! 🙏 MySQL Workbench 기준으로 Don't Limit으로 잡혀 있는 상태이긴 했는데,
조회 건수 많고 작성한 쿼리 최적화 등이 부족해서 Fetch 시간이 상대적으로 많이 나오는 것 같습니다.

2022-07-09 16:22 UTC, handh0413 commented on README.md
> +inner join member m on m.id = c.member_id;
테이블 조인을 잘못했네요.. 수정해서 다시 commit 하겠습니당

2022-07-10 00:34 UTC, handh0413 commented on README.md
> +from (select id from member where age between 20 and 29) m
코드까지 직접 작성해주셔서 감사합니다! 👍 한번 추가로 관련 내용을 공부해봐야 할 것 같습니다. 
`서울대병원에 다닌 30대 환자들을 운동 횟수별로 집계하세요. (user.Exercise)` 문제에서
보내주신 쿼리를 참고하여 비슷하게 쿼리를 추가 작성해봤는데, 아직 조금 더 공부 및 적용 연습이 필요해보입니다..

2022-07-10 00:35 UTC, handh0413 commented on README.md
> +- [x] 서울대병원에 다닌 30대 환자들을 운동 횟수별로 집계하세요. (user.Exercise)
감사합니다!

2022-07-10 04:12 UTC, seokhongkim commented on README.md
> +select c.id, h.name, p.hobby, p.dev_type, p.years_coding
동희님이 말씀해주신 내용이 맞습니다! 제가 잘못된 내용을 공유드려서 정정합니다.

intellij 로 확인하면서 항상 fetch time 이 포함된 시간을 봤고, profiling 옵션을 켜서도 세부 시간을 확인하지 않아서 잘못된 내용을 말씀드렸네요.

```sql
set profiling = 1;
// 쿼리 실행
show profiles;
show profile for query 2; // query_id 에 대한 실행 시간
```

위 방법으로 확인하여 쿼리 실행 시간 만족하는 것 확인했습니다! 👍

2022-07-10 04:15 UTC, seokhongkim approved these changes
동희님, 4단계 미션 잘 마무리 해주셨습니다. 👍 
4단계 PR 머지하도록 하겠습니다.

마지막 미션 진행하는동안 수고 많으셨습니다!
그리고 4단계 미션에서 남겨주신 코멘트를 통해, 제가 잘못 알고 있었던 내용을 바로 잡을 수 있어서 감사드립니다.
2달간의 학습 기간이 이제 끝나는데, 학습을 시작하며 목표하신 바를 달성하셨기를 바랍니다. 🙏 

추가 미션이 하나 남았는데, 시간이 되시면 진행해보셔도 도움이 될 것 같습니다. 😀

2022-07-10 04:16 UTC, merged

2022-07-10 06:07 UTC, handh0413 commented on README.md
> +select c.id, h.name, p.hobby, p.dev_type, p.years_coding
쿼리 실행까지 직접 재확인해주셔서 감사합니다! 👍