[🚀 1단계 - 화면 응답 개선하기] 리뷰 부탁드립니다.
next-step/infra-subway-performance pull request #4
Opened 2021-06-20 12:12 UTC by kwj1270

안녕하세요 리뷰어님 이번 미션 잘 부탁드립니다.    
이번 미션도 설정할게 많아서 시간이 많이 걸렸지만,    
그래도 처음으로 캐시도 사용해보고 http2로 바꾸고 정말 재밌었던 것 같아요 :)  
덕분에 매일 성장하는 느낌을 많이 받고 있어서 매우 감사드립니다. :) 

**질문**
* 개인적인 생각으로 다음 로직이 없는 조회 부문에 `@Async`를 넣는 경우가 좋을 것 같은데  
   테스트 케이스가 터져서 결국 하나도 넣지 못했습니다. 
   `@Async`를 넣어서 테스트를 할 때 따로 구현하거나 고려할 사항이 있나요?  
* `@Cacheable` 또한 테스트가 터져서 일단은 `prod`에서만 돌리도록 했습니다.
   마찬가지로 테스트를 할 때 따로 구현하거나 고려할 사항이 있나요? 
* `LocalDateTime` 같은 경우도 역직렬화가 안되기에 String 으로 돌려서 테스트를 진행했는데 또 터져서 ㅎㅎ;
   마찬가지로 테스트를 할 때 따로 구현하거나 고려할 사항이 있나요?

2021-06-21 12:19 UTC, brainbackdoor requested changes
안녕하세요! 3주차 미션에서 여러 테스트를 해보셨군요! 💯 
부하테스트와 관련하여 개선할 부분이 보여 Request Changes 했어요~
추가적으로, 캐싱, 역직렬화 등으로 인해 상황이 변경되었다면 테스트도 수정하는게 맞습니다.
가령, 응답 DTO가 LocalDateTime이 아니라 String으로 변환되었다면,
이에 맞춰 변경하는 것이 맞습니다.
몇가지 피드백 남겨두었으니 확인해보시고 궁금한 점 있으면 DM 주세요~
오늘도 고생 많으셨어요~ 🙏🏻

2021-06-21 12:19 UTC, brainbackdoor commented on README.md
> +      * `@Async`는 적용하면 테스트코드가 에러가 터져서... 적용안했습니다.
현재 지하철 노선도에서 비동기처리를 하여 성능상 개선이 생기는 부분이 있나요?
비동기에 대한 테스트를 진행하려면 테스트 코드를 수정해야 해요. 
비동기 요청에 대해 테스트코드를 작성할 떄는 보통 두가지를 고려해요
1. 비동기 요청을 하는 메서드가 호출되었는가
2. 제대로 콜백받았다고 가정했을 때 의도한대로 동작을 수행하는가

그리고 이런 부분들에 Test Double을 활용하시면 되는데요. Test Double을 사용하는 방법은 여기서 다루기엔 내용이 많을거 같네요 😅

2021-06-21 12:19 UTC, brainbackdoor commented on README.md
> +      * Cache를 로컬로 적용시켜서 테스트하면 에러가 나서 `prod`에만 적용했습니다.
Spring Data Redis 에 대한 JUnit Test는 아래 링크를 참고해보세요~ 

> https://jojoldu.tistory.com/297

2021-06-21 12:19 UTC, brainbackdoor commented on src/main/java/nextstep/subway/config/CustomJackson2JsonRedisSerializer.java
> +public class CustomJackson2JsonRedisSerializer extends Jackson2JsonRedisSerializer {
👍

2021-06-21 12:26 UTC, kwj1270 commented on README.md
> +**nginx.conf 를 수정하기 전 결과를 날려서 ㅎㅎ.. 애플리케이션에서의 성능 향상 차이만 비교될 겁니다.**
내일 중으로 시간내서 다시 작성해보겠습니다!

2021-06-21 12:52 UTC, kwj1270 commented
@brainbackdoor 
세심하게 리뷰해주신점 정말 감사합니다 :)  
사실, 이번 과정에서 진행하는 것들은 전부 처음 경험해보는 것들이라...   
이것저것 인터넷에서 찾아 적용하기 바빴던 것 같아요     
특히 이번 미션은 개념이 붕 뜬 느낌이 좀 많은데 내일이랑 내일 모레 중으로 제대로 정리하고 다시 PR 드리겠습니다!!

2021-06-24 14:31 UTC, brainbackdoor approved these changes
피드백 반영하셔서 개선 사항들을 세부적으로 나누고 진행하셨던 점, 서버를 증설하여 부하분산한 점, Stress 테스트를 통해 한계점을 계측한 점 등이 인상적이네요! 💯 
다음 단계도 진행해보시고 또 인사이트 얻으가시면 좋겠네요~
고생하셨어요~

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +* 1일 사용자 수 : 183_000 (5_490_000 / 30)
왜 30으로 나눴나요? 혹시 위의 수치는 mau일까요?

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +* 구글 지도(코리아) DAU 를 기준 : 549만
경쟁사를 벤치마킹했군요!

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +3. 용산 -> 강남 출근길 회사 경로 탐색
👍 
유저 시나리오를 기반으로 구성하셨네요~

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +[k6 rps 계산 공식 방법](https://k6.io/blog/ref-how-to-generate-a-constant-request-rate-in-k6/)
💯

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +이때부터 테스트가 통과되었습니다.
👍

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +     http_reqs......................: 281154  1561.879527/s
극적인 성능개선이 있었군요!

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +`1080VU` 에서 에러가 발생하는걸 알았습니다.
💯

2021-06-24 14:31 UTC, brainbackdoor commented on README.md
> +      * http2 를 사용하도록 했습니다 -> http2 를 개선만해도 꽤나 좋아지더라고요
💯

2021-06-24 14:32 UTC, merged