[Step 1] 화면 응답속도 개선하기
next-step/infra-subway-performance pull request #411
Opened 2022-12-15 12:55 UTC by sawooook

안녕하세요 리뷰어님!

STEP1 화면 응답 속도 개선하기 PR 드립니다!!

잘부탁드립니다  🙇

2022-12-15 15:28 UTC, heowc requested changes
안녕하세요. 리뷰어를 맡은 허원철입니다 🙇 

벌써 마지막 단계를 진행중 이시네요 👍 
대단하십니다. 마지막까지 열심히 해보아요~

소소하게 몇가지 코멘트를 달아보았습니다.
확인 드리고, 궁금하신 점이나 의논할 것이 있다면 깃헙 코멘트나 슬랙 DM 으로 연락주세요 🙏


-----

부하테스트 관련 스크립트가 어딨는지 못찾겟는데 혹시 어디서 확인 할수 있을까요? 🤣

2022-12-15 15:28 UTC, heowc commented on src/main/java/nextstep/subway/common/CacheConfig.java
> +                .serializeValuesWith(fromSerializer(new GenericJackson2JsonRedisSerializer()));
TTL이 필요하진 않을까요 🤔

2022-12-15 15:28 UTC, heowc commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    private final LineRepository lineRepository;
이것만 `final`을 추가하신 이유가 있을까요 🤔

2022-12-15 15:28 UTC, heowc commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            @CacheEvict(cacheNames = paths, allEntries = true),
두가지 질문이 있습니다 😄 

1. 실제 프로덕션 환경에서 캐싱을 사용해보신 적이 있으실까요?

2. `allEntries`을 사용해보았는지? 어떤 이유로 추가했는지? 고려사항은 없을지? 확인부탁드려요 👍

2022-12-17 16:29 UTC, sawooook commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            @CacheEvict(cacheNames = paths, allEntries = true),
1.  넵 적용해본적있습니다~!
2. allEntries는 사용해본적없습니다! 
   +  추가한이유는 새롭게 라인 값이 추가되었기 때문에, 경로 값이 바뀔 수 있기때문에 기존 캐시를 제거하였습니다..!
   + 고려사항은 기존 캐시를 전부 지워버리기 때문에 다시 새롭게 캐싱을 해야하는 고려사항이 있습니다..!

2022-12-17 16:29 UTC, sawooook commented on src/main/java/nextstep/subway/common/CacheConfig.java
> +                .serializeValuesWith(fromSerializer(new GenericJackson2JsonRedisSerializer()));
필요한 부분 같습니다.. ㅎㅎ! 감사합니다~!

2022-12-18 00:27 UTC, sawooook commented
안녕하세요 원철님~! 제가 스크립트를 빼먹고 푸쉬한것 같습니다 해당 부분 추가하였습니다!! 테스트는 고정값으로 길을 찾지 않게끔 등록한 역에서 랜덤으로 값을 뽑아 사용하도록 하였습니다..! 테스트 시나리오 또한 로그인한 시나리오, 비로그인한 시나리오 2가지로 나눠서 진행해보았습니다

2022-12-18 02:46 UTC, heowc commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            @CacheEvict(cacheNames = paths, allEntries = true),
`allEntries`이 어떤 방식으로 cache evict 하는지 찾아보시면 더욱 도움이 될 것 같아요
조금 더 힌트를 드리자면 redis의 keys 커멘트 활용법에 대해 고민해보셨다면 아실 수 있을 듯 해요~

2022-12-18 02:47 UTC, heowc commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            @CacheEvict(cacheNames = paths, allEntries = true),
> 지하철 이라는 특성상 새로운 Line이나 Station이 추가 될일은 거의 드물기 때문에 상관 없다고 생각하여 괜찮다고 생각하였습니다..!

저도 동일한 생각입니다 👍 
저도 서비스 특성상 CUD가 거의 없기 때문에 과하지 않다고 생각됩니다

2022-12-18 02:50 UTC, heowc approved these changes
잘 반영해주셔서 바로 merge하도록 하겠습니다.

고민해보면 좋을 것 같은 것을 코멘트로 남겨봤는데 시간 날 때 찾아보시면 도움이 될 것 같아요 👍 
다음 단계를 진행해주세요

2022-12-18 02:50 UTC, heowc commented on src/main/java/nextstep/subway/common/CacheConstant.java
> +    public static final Long cacheTTLByDay = 1L;
하루로 ttl을 주신 이유가 궁금합니다~

2022-12-18 02:50 UTC, heowc commented on k6/smoke/Smoke.js
> +  let target = targetRandomNumber();
랜덤 적용 👍

2022-12-18 02:50 UTC, merged

2022-12-19 16:31 UTC, sawooook commented on src/main/java/nextstep/subway/common/CacheConstant.java
> +    public static final Long cacheTTLByDay = 1L;
아 하루를 적용한 이유는 경로 찾기 기준으로 생각 하여 하루를 주었는데요..!
지금 든 생각은 station, line 같은 캐싱은 7일을 주고, path 에만 하루를 줄 것 같습니다!
station, line 같은 경우 잘 변하지 않는 캐시이니 조금 길게 가져가고 path의 경우 유저가 검색할떄마다 캐싱이 되니 많이 쌓일것같아 하루를 기준으로 가져갈것같습니다..!

2022-12-19 16:44 UTC, sawooook commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            @CacheEvict(cacheNames = paths, allEntries = true),
찾아보니 allEntries가 keys 로 구현된 구현체도 있었군요 ...!  서비스에 잘 알지못하고 적용했으면  REDIS 병목 현상이 발생 했을수도 있었겠습니다..!  모르고 지나칠뻔 했습니다 ...! 감사합니다 🙇