[Step2] 2단계 - 스케일 아웃 (with ASG)
next-step/infra-subway-performance pull request #451
Opened 2022-12-19 17:06 UTC by sawooook

안녕하세요 원철님!

2단계 스케일 아웃 PR 드립니다~!

ec2가 늘어나는걸 눈으로 보니까 신기하고 재미있었습니다~!

이번에도 잘부탁드립니다 감사합니다 🙇

2022-12-20 13:54 UTC, heowc requested changes
안녕하세요~ 빠르게 2단계를 진행해주셨지만, 한번 짚고 넘어야할 부분이 있어서 request changes 를 드렸습니다.

코멘트 확인해보시고 궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

----

원래는 베스천을 통해서 각각의 인스턴스를 접근해야하는데 지금은 모든 인스턴스를 접근할 수 있는 것으로 보이는데.. 이것도 확인 부탁드릴게요 🤣

2022-12-20 13:54 UTC, heowc commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://192.168.26.135:3306:3306/subway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
```suggestion
spring.datasource.url=jdbc:mysql://192.168.26.135:3306/subway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
```

2022-12-20 13:54 UTC, heowc commented on src/main/java/nextstep/subway/common/WebMvcConfig.java
> +        resourceHandlerRegistry.addResourceHandler(PREFIX_STATIC_RESOURCES + "/" + subwayVersionSupport.getVersion() + "/**")
잘 설정해주셨습니다. 다만 테스트 코드가 없는 것 같아요 🤣

2022-12-20 13:54 UTC, heowc commented on src/main/java/nextstep/subway/common/WebMvcConfig.java
> +public class WebMvcConfig implements WebMvcConfigurer {
`미션3: 모든 정적 자원에 대해 no-cache, no-store 설정을 한다. 가능한가요?`

에 대한 결론이 없는 것 같습니다 🤔

2022-12-20 13:54 UTC, heowc commented on src/main/resources/static/css/app.css
> +body {
적을 곳이 마땅하지 않아 여기다가 코멘트 달아두겠습니다 😄 

1. taget group에 health가 내려가 있습니다. 실질적으로 elb를 통해 트래픽이 정상적으로 들어가지 않는 것 같아요~
  - 페이지 접속 후, 역 조회를 해보면 500 에러가 발생해요.
2. `https://sawooook-webservice.p-e.kr` 에 접속하면 의도한대로 라면 `/resources/{version}`이여야 하는데 이전과 동일하게 동작합니다. 예상해보자면, 기존에 nginx에 캐싱된게 응답되는 것 같아요~ 사실상 이제는 nginx가 필요가 없어진 상태입니다.
3. 오토 스케일링이 정상 동작하지 않는 것 같아요. 물론, 부하를 일으켜 인스턴스 자체는 생성이 되었지만, elb에 인스턴스가 정상적으로 연결이 되지 않는 것 같아요.
4. smoke, load, stress 테스트 라고 하기엔 서로 비슷한 VUser를 갖고 테스트가 된 것 같아요. 실질적으로 stress를 통해 오토스케일링으로 보다 많은 트래픽을 받을 수 있어야 함을 증명하려면 어떻게 스크립트를 작성해야 할까요 🤔   
5. 이건 참고만 해주셨으면 하는 부분인데요. template을 보니 도커 설치와 더불어 redis을 별도로 띄우고 있는 것 같습니다. 그렇게 되면 매인스턴스마다 redis가 새로 만들어질텐데 의도하신 부분일까요? 🤔

2022-12-21 17:17 UTC, sawooook commented
원철님 안녕하세요~!

베스쳔 서버로 접근 가능하도록 보안그륩 수정도 해보았습니다 잘부탁드립니다 🙇

2022-12-21 23:35 UTC, heowc approved these changes
빠르게 피드백을 반영해주셨네요 👍 
고생히셨습니다.

피드백을 잘 반영해주셔서 바로 merge 하도록 하겠습니다.
다음 단계를 진행해주세요 💯

2022-12-21 23:35 UTC, heowc commented on src/test/java/nextstep/subway/web/StaticResourceTest.java
> +    void staticImageResources() {
테스트 코드 작성 👍

2022-12-21 23:35 UTC, heowc commented on README.md
> +3. 모든 정적 자원에 대해 no-cache, no-store 설정을 한다. 가능한가요?
👍  잘 정리해주셨어요 👍

2022-12-21 23:35 UTC, heowc commented on src/main/resources/static/css/app.css
> +body {
👍 잘 정리해주셨습니다 👍

2022-12-21 23:35 UTC, merged