4단계 인덱스 설계(+ 추가 미션)
next-step/infra-subway-performance pull request #515
Opened 2022-12-23 08:01 UTC by cwJohnPark

안녕하세요 석홍님!
드디어 마지막 미션이네요.

인덱스 설계를 쿼리별로 쪼개어 해보았습니다!
인덱스를 어디에 적용하느냐와 드라이빙/드리븐 테이블이 어느 쪽으로 결정되느냐가 중요하다는 것을 배웠습니다.

페이징과 레플리케이션을 Spring에서 적용하는 것은 평소에 궁금하던 내용이라 추가 미션까지 실습해보았습니다.

밤을 꼬박 지새우며 과제를 하던 날들이 엊그제 같은데 벌써 마지막이라니 아쉽습니다.

어색한 부분이나 고칠점있으면 피드백 부탁드리겠습니다!
감사합니다!

2022-12-23 14:38 UTC, seokhongkim requested changes
창원님, 4단계 미션 잘 진행해주셨습니다. 👍 
인덱스 추가하신 쿼리까지 함께 첨부해주시면 쿼리는 한번 더 확인해보고 코멘트 남기겠습니다.
이외에 코멘트 남긴 내용도 함께 확인 부탁드립니다. 🙏

2022-12-23 14:38 UTC, seokhongkim commented on README.md
> +FROM (SELECT id, name
가능하면 쿼리를 작성하실 때 join 을 이용해서 작성하시는 것을 추천합니다.
쿼리 튜닝하기 문서의 마지막 내용을 참고해보셔도 좋겠습니다.
> https://edu.nextstep.camp/s/urD8knTu/ls/KlVoD5j4

2022-12-23 14:38 UTC, seokhongkim commented on README.md
> +    AND covid.id = user.id
`covid.programmer_id`와 `user.id` 가 같은 조건이어야 할 것 같네요!

2022-12-23 14:38 UTC, seokhongkim commented on README.md
> +	OR years_coding like '0%'
`years_coding` 컬럼의 값을 확인해봤을 때 0-2년차를 나타내는 값으로는 `0-2 years` 라는 하나의 값만 있는데, `like` 조건으로 작성하신 이유가 있을까요? :)

2022-12-23 14:38 UTC, seokhongkim commented on README.md
> +	( SELECT member_id, stay
`stay` 컬럼도 조회하신 이유가 있을까요?

2022-12-23 14:38 UTC, seokhongkim commented on src/main/java/nextstep/subway/common/infra/DatabaseConfig.java
> +@EnableJpaAuditing
`Auditing` 도 사용하도록 설정하신 이유가 있을까요?

2022-12-23 14:38 UTC, seokhongkim commented on src/main/java/nextstep/subway/common/infra/DatabaseConfig.java
> +    public DataSource routingDataSource(@Qualifier("masterDataSource") DataSource master,
`ReplicationRoutingDataSource`, `LazyConnectionDataSourceProxy` 이용해서 readOnly일 때, replication DB 사용하도록 설정 잘 해주셨습니다. 👍

2022-12-23 14:38 UTC, seokhongkim commented on src/main/java/nextstep/subway/common/profile/ProfileType.java
> +public enum ProfileType {
프로필 사용과 관련하여 나중에 여유가 되실 때, https://reflectoring.io/dont-use-spring-profile-annotation/ 글을 읽어보셔도 좋겠습니다. :)

2022-12-23 14:38 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    public List<LineResponse> findLineResponses(Pageable pageable) {
`Pageable` 인터페이스를 활용한 페이징 학습 좋습니다. 👍 
`[추가] 페이징, Replication` 문서에서 보셨겠지만, 이 방법은 오프셋 기반으로 데이터 양이 많을 때 뒷 페이지를 조회할수록 성능이 낮아질 수 있습니다. 관련해서 `커서 기반 페이지네이션`, `no offset paging` 등의 키워드로 학습해보시거나 https://jojoldu.tistory.com/528 블로그의 내용을 읽고 학습해보셔도 좋겠습니다. :)

2022-12-24 00:50 UTC, cwJohnPark commented on README.md
> +- Coding as a Hobby 와 같은 결과를 반환하세요.
추가하였습니다!

2022-12-24 02:09 UTC, cwJohnPark commented on README.md
> +- 프로그래머별로 해당하는 병원 이름을 반환하세요. (covid.id, hospital.name)
인덱스 추가 쿼리도 작성하였습니다!

2022-12-24 02:17 UTC, cwJohnPark commented on README.md
> +SELECT c.id, h.name
programmer 테이블에 대한 조인 추가하였습니다!

2022-12-24 02:21 UTC, cwJohnPark commented on README.md
> +FROM (SELECT id, name
JOIN 사용해서 수정해보겠습니다!

2022-12-24 02:26 UTC, cwJohnPark commented on README.md
> +    AND covid.id = user.id
covid 의 id가 아니라 programmer_id 였군요.
수정했습니다!

2022-12-24 02:26 UTC, cwJohnPark commented on README.md
> +FROM (SELECT id, name
훨씬 깔끔해진것 같습니다.
수행속도는 차이가 없네요.
```
SELECT covid.programmer_id,
       hospital.name,
       user.hobby,
       user.dev_type,
       user.years_coding
FROM
(	
		SELECT id, years_coding, hobby, student, dev_type
		FROM programmer
		WHERE 
		(hobby = 'Yes' AND student like 'Yes%')
		OR 
		years_coding like '0%'
) user 
INNER JOIN covid ON user.id = covid.programmer_id
INNER JOIN hospital ON covid.hospital_id = hospital.id
;
--

SELECT covid.programmer_id,
       hospital.name,
       user.hobby,
       user.dev_type,
       user.years_coding
FROM(
      (
        SELECT id, name
        FROM hospital
      ) hospital,
	(	
		SELECT programmer_id, hospital_id
		FROM covid
	) covid ,
    (	
		SELECT id, years_coding, hobby, student, dev_type
		FROM programmer
		WHERE 
		(hobby = 'Yes' AND student like 'Yes%')
		OR 
		years_coding like '0%'
	) user
      )
WHERE hospital.id = covid.hospital_id
  AND covid.programmer_id = user.id
;
```

2022-12-24 02:28 UTC, cwJohnPark commented on README.md
> +	OR years_coding like '0%'
0-2 years 이외에 값이 있는줄 착각했네요. 
'0-2 years' 고정 값으로 수정하였습니다.

2022-12-24 02:29 UTC, cwJohnPark commented on README.md
> +	( SELECT member_id, stay
필요없는 칼럼이군요.
제거 하였습니다!

2022-12-24 02:48 UTC, cwJohnPark commented on src/main/java/nextstep/subway/common/infra/DatabaseConfig.java
> +@EnableJpaAuditing
기존 코드에 설정이 되어있어서 그대로 유지하였습니다!

2022-12-24 02:49 UTC, cwJohnPark commented on src/main/java/nextstep/subway/common/infra/DatabaseConfig.java
> +@EnableJpaAuditing
Jpa 관련 설정은 별도 설정 클래스로 분리하였습니다.

2022-12-24 02:51 UTC, cwJohnPark commented on src/main/java/nextstep/subway/common/profile/ProfileType.java
> +public enum ProfileType {
코드 레벨에서 설정 쪽으로 의존되어버리기 때문에 사용을 지양해야 하군요!
```
The main issue I see with the @Profile annotation is that it spreads dependencies to the profiles across the codebase.
```

2022-12-24 03:04 UTC, cwJohnPark commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    public List<LineResponse> findLineResponses(Pageable pageable) {
😮 처음 보는 내용이네요.
한단계 더 성능을 고려할 수 있었군요.
전혀 몰랐던 내용인데 알려주셔서 감사드립니다!

2022-12-24 04:18 UTC, seokhongkim requested changes
창원님, 4단계 코멘트 잘 반영해주셨습니다. 👍 
인덱스와 쿼리 이용해서 확인 후 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-12-24 04:18 UTC, seokhongkim commented on README.md
> +                  ON covid.programmer_id = programmer.id
`programmer` 테이블과 조인이 추가되면서 실행 시간이 3초 넘게 걸리는 것 같습니다. (맥북프로 intel i9 23GHz 8코어 cpu, 32GB 메모리 기준)
확인 부탁드립니다. :)

2022-12-24 04:18 UTC, seokhongkim commented on README.md
> +INNER JOIN covid ON user.id = covid.programmer_id
이 쿼리도 `programmer` 테이블과 조인을 위한 인덱스가 없어서 실행 시간이 오래 걸리는 것으로 보이네요!

2022-12-24 04:18 UTC, seokhongkim commented on README.md
> +;
`user.id` 기준 정렬 조건이 빠진 것 같습니다.

2022-12-24 04:18 UTC, seokhongkim commented on README.md
> +SELECT covid.programmer_id,
`covid.id`를 출력해야 하는 것으로 보이네요!

2022-12-24 04:18 UTC, seokhongkim commented on README.md
> +SELECT stay, count(stay)
이 쿼리는 제 노트북으로는 150-200ms 정도의 속도가 나오는 것으로 보이네요.
창원님 PC에서 쿼리 한번 더 확인 부탁드립니다. 실행 후 100ms 이내로 나온다면 넘어가셔도 될 것 같습니다. :)

2022-12-24 04:18 UTC, seokhongkim commented on README.md
> +SELECT exercise, count(exercise) as exercise_count
이 쿼리에 사용한 인덱스는 아래 3개의 인덱스가 맞을까요?
```sql
CREATE INDEX idx_programmer_exercise ON programmer(exercise);
CREATE INDEX idx_programmer_member_id on programmer(member_id);
CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
```

이렇게만 추가했을 때는 5초 이상의 시간이 걸리는 것으로 보이네요. 😢 
혹시 이전 단계에서 설정한 인덱스도 함께 사용하는 것일까요? `idx_covid_hospital_id`가 있어서 다른 인덱스는 모두 제거했는데, 이전 단계에서 설정한 인덱스도 사용한다면 말씀 부탁드립니다.

2022-12-24 09:29 UTC, seokhongkim approved these changes
창원님, 4단계 미션 잘 마무리해주셨습니다. 👍
4단계 PR 머지하겠습니다.

이번 미션을 끝으로 마지막 미션이 종료되네요.
학습 기간동안 창원님이 목표하신 학습과 성장을 달성하셨기를 바랍니다. 🙏
2달의 시간동안 학습과 미션 진행하느라 수고 많으셨습니다. 👏

2022-12-24 09:29 UTC, seokhongkim commented on README.md
> +                  ON covid.programmer_id = programmer.id
인덱스 설정 잘 되었고, 쿼리 실행 결과와 시간 모두 미션 요구사항 만족하는 것 확인했습니다. 👍

2022-12-24 09:29 UTC, seokhongkim commented on README.md
> +;
데이터를 저장할 때 순서대로 저장하면서 동일한 id를 가지고 있도록 생성되었을 수 있을 것 같네요! :) 데이터 확인 후 대체 컬럼을 사용하신 것 좋습니다.
나중에 실무에서는 동일한 값이 있는 것으로 보이는 컬럼도 달라질 수 있으므로, 명시적으로 목적에 맞는 컬럼을 사용하시는 것을 추천 드립니다.

2022-12-24 09:29 UTC, seokhongkim commented on README.md
> +SELECT covid.id,
인덱스 설정 잘 되었고, 쿼리 실행 결과와 시간 모두 미션 요구사항 만족하는 것 확인했습니다. 👍

2022-12-24 09:29 UTC, seokhongkim commented on README.md
> +SELECT stay, count(stay)
인덱스 설정 잘 되었고, 쿼리 실행 결과와 시간 모두 미션 요구사항 만족하는 것 확인했습니다. 👍

2022-12-24 09:29 UTC, seokhongkim commented on README.md
> +SELECT exercise, count(exercise) as exercise_count
인덱스 설정 잘 되었고, 쿼리 실행 결과와 시간 모두 미션 요구사항 만족하는 것 확인했습니다. 👍

2022-12-24 09:29 UTC, merged