🚀 2단계 - 조회 성능 개선하기
next-step/infra-subway-performance pull request #73
Opened 2021-07-14 10:25 UTC by ini8262

2021-07-16 09:28 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드립니다.

2021-07-16 09:28 UTC, kingbbode commented on README.md
> +    ```
`covid` 에 추가적인 인덱스가 더 필요할 것으로 보입니다.

2021-07-16 09:28 UTC, kingbbode commented on README.md
> +    order by user.id
인덱스가 부족해보입니다.

2021-07-16 09:28 UTC, kingbbode commented on README.md
>  1. 인덱스 적용해보기 실습을 진행해본 과정을 공유해주세요
어떤 인덱스를 설정했는지 구체적으로 작성해주시면 좋을 듯 합니다 :) 변경 전후 ddl 을 첨부해주셔도 좋습니다.

인덱스를 설정하고 실행계획이 어떻게 변화했는지 첨부 부탁드립니다.

2021-07-17 06:14 UTC, ini8262 commented on README.md
>  1. 인덱스 적용해보기 실습을 진행해본 과정을 공유해주세요
실습을 진행한 과정이 공유된 자료가 부족할건 느끼고, 변경전, 후에 `DDL`을 추가하였습니다.

2021-07-17 06:16 UTC, ini8262 commented on README.md
> +    ```
실습을 모두 진행한 이후에, 공유과정을 작성하느라, 빠트린 내용이 있었네요. 😢 설명 추가하였습니다.

2021-07-17 06:16 UTC, ini8262 commented on README.md
> +    order by user.id
실습을 모두 진행한 이후에, 공유과정을 작성하느라, 빠트린 내용이 있었네요. 😢 설명 추가하였습니다.

2021-07-18 04:36 UTC, kingbbode commented
전체적으로 인덱스가 많이 모자라네요 :)
실행계획을 보고 계신지 궁금합니다.
개선하시어 실행계획에 대한 변화를 첨부 부탁드립니다.

2021-07-18 04:36 UTC, kingbbode requested changes
코멘트 작성해두었습니다.
확인 부탁드려요 :)

2021-07-18 04:55 UTC, ini8262 commented
혹시 어느부분이 부족한건가요?
실행계획을 통해서 인덱스 실습을 진행하였습니다. 
인덱스 잡기 [전후의사진을 커밋](https://github.com/next-step/infra-subway-performance/pull/73/commits/888ea5a931900430ef02b5e0c818119fedabfa46#diff-e433a49c7ca75ac063c3a9110943171d3b482bb5928897c7d9c538328df6b21b)하였습니다. 확인 부탁드립니다.

2021-07-18 05:48 UTC, kingbbode approved these changes
고생많으셨습니다 :)
머지하겠습니다.

2021-07-18 05:48 UTC, kingbbode commented on README.md
> +    ```
group by 로 인한 filesort 도 제거해보셨으면 좋았을 듯 합니다 :)

2021-07-18 05:48 UTC, merged

2021-07-18 06:36 UTC, ini8262 commented on README.md
> +    ```
피드백 감사합니다. [group by 로 인한 filesort 제거](http://intomysql.blogspot.com/2010/12/group-by-filesort.html) 진행하였습니다!

2021-07-19 04:13 UTC, ini8262 commented
![image](https://user-images.githubusercontent.com/23042969/126101815-17b08bb9-7825-4a84-a0a3-8a1ff80d20d9.png)