[STEP2] 조회 성능 개선하기
next-step/infra-subway-performance pull request #76
Opened 2021-07-14 16:40 UTC by 7271kim

안녕하세요  용근님 :)
바쁘신건 어느정도 마무리 되셨나요!
바쁘신 와중에도 리뷰 해주시는게 참 감사하네요 ㅠ

STEP2 마지막 미션 완료하여 리뷰 요청드립니다 😄 
SQL은 아직 부족하지만, 원하는 속도가 나오 도록 튜닝 성공하면 기분 좋네요 😃 
용근님이 보시기에 더 효율적이라고 생각되는 쿼리가 있다면 말씀해주세여 ㅎㅎ 
또한 페이징 쿼리와 JPQL을 통해서 특정 id부터 찾도록 작업했고,  DB Master, Slave 를 통해 부하 분산이 잘 되도록하였고 동기화까지 확인했습니다 ~ 테스트용 DB로만 하다가 Master Slave 작업할 겸  이전에 했던 flyway 적용하면서 이전 데이터들 다 들고왔습니다.

추가로 이전에 리뷰주셨던 
 - "GenericJackson2JsonRedisSerializer 에 LocalDateTime 을 잘 처리해줄 수 있는 ObjectMapper 로 넣기"
 - "REDIS_KEY 상수제거"
도 완료했는데 한번 리뷰해주신 의도대로 잘 되었는지 확인 부탁드려요 ㅎㅎ 

2달동안 많이 배웠는데 마지막이라고 생각하니 뭔가 아쉽네요 ㅠ

2021-07-16 09:46 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드립니다.

2021-07-16 09:46 UTC, kingbbode commented on README.md
> +ii) 문제 : 큰 이슈 없음
개선할 내용이 있어보이네요 :)

2021-07-16 09:46 UTC, kingbbode commented on README.md
> +CREATE INDEX idx_covid_all ON subway.covid(hospital_id, programmer_id, member_id);
개선이 필요해보입니다 :)

2021-07-16 09:46 UTC, kingbbode commented on README.md
> +#### 1. 인덱스 적용해보기 실습을 진행해본 과정을 공유해주세요
개선이 추가로 필요하거나, 효율적이지 못한 인덱스가 추가된 부분에 코멘트를 달아두었습니다.

실행계획을 보고 계신지가 궁금합니다.
이후 개선에서부터는 실행계획의 변화도 기록해주시면 감사하겠습니다.

2021-07-16 16:31 UTC, 7271kim commented
안녕하세요 용근님!
불금 잘보내고 계신가요 ㅎㅎ 이번 한 주도 끝났네요 😄 
리뷰관련 From절과 Join절의 모수를 줄이도록 노력하였고 추가적인 index 추가 했습니다.
의도하신 부분이 맞는지 확인 부탁드립니다.

단 의문점은 실행 계획을 안보고 있다고 말씀해 주셨는데, 
개선이 필요하다고 리뷰받은 실행 계획 중에 어떤 부분을 보고 실행 계획을 안보고 있다고 판단하셨는지 알 수 있을까요?
수정 전 실행계획들 README.md 이미지로 첨부하였습니다 :) 

작업 당시 쿼리 실력이 부족하다 생각되어 여러 인덱스 추가와 여러 쿼리를 짜보면서 내린 최종 결론이 '인덱스는 전체가 타야하고, 추가된 인덱스 수는 적어야 하며, 쿼리는 보기좋게' 3개를 기준으로 가정 적합하다고 생각된 쿼리를 적은 것이거든요 ㅠ 

한번 확인 부탁드립니다.
감사합니다.

2021-07-17 01:38 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-07-17 01:38 UTC, kingbbode commented on README.md
> +CREATE INDEX idx_covid_all ON subway.covid(hospital_id, programmer_id, member_id);
`idx_covid_all` 은 재활용 가능한 인덱스인가요?
`programmer_id`, `member_id` 를 사용하는 쿼리에서 이 인덱스는 효율적이게 동작하나요?
필요한 것은 `fk` 를 대체하는 인덱스이지 않을까요.

2021-07-17 01:38 UTC, kingbbode commented
실행 계획을 안보고 있다고 판단한 것이 아니라, 실행 계획을 함께 첨부해주셨으면 하여 말씀드렸어요 :)

2021-07-17 04:27 UTC, 7271kim commented
안녕하세요 용근님!
전 인덱스를 타고 있지 않다는 시점으로 바라보았는데 다른 부분을 말씀해주셨던 거군요 :)

말씀하신 부분에서 
CREATE INDEX idx_covid_all ON subway.covid(hospital_id, programmer_id, member_id); 에서 
programmer_id, member_id 를 사용하는 쿼리에서는 효율적으로 동작하지 않습니다.
hospital_id가 먼저 탐색이 되어야 하기 때문에 문제가 있죠..

다시보니 

기존 
CREATE INDEX idx_covid_all ON subway.covid(programmer_id, hospital_id);

이슈
**기존부분을 DROP 시키고 새로 생성하면서 순서를 망치고 있음** 
CREATE INDEX idx_covid_all ON subway.covid(hospital_id, programmer_id, member_id);

가 되고 있었던걸 이제 확인했습니다ㅠ
원래 의도는 순서는 유지하고 맨 마지막 항목을 추가하는 것을 하고 싶었는데 잘못하고 있었습니다
idx_covid_all로 네이밍을 하다보니 무엇이 들어갔는지 대략적 유추도 못하는 문제가 있군요!

꼼꼼한 리뷰 감사드립니다 👍 
전체적으로 쿼리 다시 보면서 인덱스 수정 다시 하였습니다 :) 
다시 한번 확인 부탁드립니다~
감사합니다 :)

2021-07-17 15:45 UTC, kingbbode approved these changes
고생 많으셨습니다 :)
이만 머지하겠습니다.

2021-07-17 15:46 UTC, merged