Step2 리뷰요청드립니다
next-step/infra-subway-performance pull request #94
Opened 2021-07-18 07:26 UTC by jeongminkyo

안녕하세요 리뷰어님

step1에서 피드백 주신 내용 반영했습니다. 구간 추가 및 삭제시 캐시 키값까지 알기가 힘들어서 path의 namespace에 있는 모든 키값을 삭제하도록 수정했습니다.

그리고 인덱스 적용해보기 실습 중에 동일 쿼리를 수행하더라도, 수행시간이 조금씩 달라지던데 이거는 쿼리 캐싱 때문에 그런걸까요 ?

2021-07-18 07:36 UTC, JunilHwang requested changes
안녕하세요 민교님! 페이징 관련해서 리뷰 하나 남겼으니 확인해보시면 될 것 같습니다.
그리고 질문 주신 내용은 아마 민교님이 이야기하시는 것 처럼 캐싱때문이라 생각합니다.

2021-07-18 07:36 UTC, JunilHwang commented on src/main/java/nextstep/subway/favorite/domain/FavoriteRepository.java
> +    List<Favorite> findByMemberId(Long memberId, Pageable pageable);
![image](https://user-images.githubusercontent.com/18749057/126059486-590458d7-d37f-43fc-9fa5-d27f0df8e371.png)

미션 문서에 나와있는 것 처럼 특정 인덱스 부터 탐색할 수 있도록 작성해보세요!

2021-07-18 08:59 UTC, jeongminkyo commented on src/main/java/nextstep/subway/favorite/domain/FavoriteRepository.java
> +    List<Favorite> findByMemberId(Long memberId, Pageable pageable);
리뷰어님 안녕하세요 몇가지 질문드릴께 있는데, 테이블의 pk를 where 조건에 넣을려고 봤더니 해당 쿼리의 경우, 멤버의 즐겨찾기를 가져오는거라서 where 조건에 member_id가 들어가는데요, 여기서 pk에 where 조건을 추가하면 id index 값에 따라 원하는 결과값이 나오지 않을 수도 있을거 같아보여서요
ex)  
1번 즐겨찾기 id 30
2번 즐겨찾기 id 35
3번 즐겨찾기 id 45
4번 즐겨찾기 id 46
5번 즐겨찾기 id 56
6번 즐겨찾기 id 58
이라고 하면 id 값에 따라 2번에서 6번이 나올 수도 3번에서 6번이 나올 수도 있을거 같은 생각이 들어서요.클라이언트 변경이 없이 수정해야되는 경우, 이 id값은 어떻게 그리고 어떤 값이 들어가면 좋을지 궁금해서 문의드립니다

2021-07-19 13:05 UTC, jeongminkyo commented on src/main/java/nextstep/subway/favorite/domain/FavoriteRepository.java
> +    List<Favorite> findByMemberId(Long memberId, Pageable pageable);
@JunilHwang

2021-12-19 13:08 UTC, closed without merging